### ISSUE TITLE
Allow metrics to bind to non-localhost port

### ISSUE THREAD

**Issue by mtlynch** [benbjohnson/litestream#101]
It seems like the user can currently only bind the [metrics endpoint](https://litestream.io/reference/config/#metrics) to the non-localhost port.

For development on VMs or Docker, this creates a bit of an obstacle. There are ways around it but it'd be cool if the config accepted a line like this to listen on all interfaces:

```yaml
addr: "0.0.0.0:9090"
```

**Comment by benbjohnson** [comment]
I'm surprised that doesn't work. The config Addr field is passed directly into http.ListenAndServe(). I'll take a look and see what's going on.

**Comment by mtlynch** [comment]
Oh, it maybe does. I was thrown off by the log message that declared `localhost` no matter what I typed. 

https://github.com/benbjohnson/litestream/blob/cafa0f594265f81fad1f4e9639fbc9dcda6897c5/cmd/litestream/replicate.go#L119

Looking at the code, it looks like it's a log message bug rather than a functional bug:

**Comment by benbjohnson** [comment]
Ah, that makes sense. That’s an easy fix. I wanted to make sure there was a host in there but I shouldn’t be throwing out an existing host. 👍

**Comment by benbjohnson** [comment]
@mtlynch I fixed this up with https://github.com/benbjohnson/litestream/pull/103. Feel free to reopen if you have any issues with it. 👍
