### ISSUE TITLE
Allow environment variables without "AWS" prefix

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#125]
Currently, the access key & secret key can be specified using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. However, this can be confusing if the user is not using `AWS`. Litestream should also be able to accept `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY`.

**Comment by supermarin** [comment]
Prefixing them with LITESTREAM_ would be preferred IMO, it'll probably be stored alongside with other secrets and might be confusing which service the key belongs to.

**Comment by benbjohnson** [comment]
`LITESTREAM_ACCESS_KEY_ID` & `LITESTREAM_SECRET_ACCESS_KEY` have been added via #169
