### ISSUE TITLE
Add TLS Skip Verify Option

### ISSUE THREAD

**Issue by cablespaghetti** [benbjohnson/litestream#126]
There's a use case for having Litestream talk to TLS secured bucket endpoints (such as MinIO) where it doesn't trust the certificate. Particularly in a dev environment. It would be great to add a CLI and config file option to skip TLS verification both for ignoring certificate trust and ignoring the hostnames in the certificate.

**Comment by benbjohnson** [comment]
Thanks for submitting this, Sam. I fixed it up in https://github.com/benbjohnson/litestream/pull/141 and it's in `main` now.
