### ISSUE TITLE
Azure Blob Storage integration

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#134]
Azure Blob Store does not provide an S3-compatible API so in the short term support would need to be added via [S3Proxy](https://github.com/gaul/s3proxy) or via [MinIO's azure gateway](https://min.io/solutions/azure-s3-api-integration). Eventually, native integration with Azure Blob Storage should be added.

**Comment by simongottschlag** [comment]
Hi @benbjohnson!

I would be willing to give this a try if you want external help. I would most likely need some help but I think I would be able to do most of the work with review and recommendations from you.

Something you are interested in?

**Comment by benbjohnson** [comment]
Hi @simongottschlag! 

I really do appreciate the offer but I'm [not taking external contributions](https://github.com/benbjohnson/litestream#open-source-not-open-contribution) on Litestream right now. I'm doing some refactoring on the replica system right now so hopefully adding new replica types should be relatively easy after that. I'd love some feedback on it when it's done though.

**Comment by simongottschlag** [comment]
Hi @benbjohnson 😁

Sorry for missing that, fully understandable. 😊 I'll keep an eye on this issue and feel free to ping me if you want someone to test or feedback on Azure and their authentication.

I can recommend taking a look at this library, which is what Terraform is using for the remote state integration: https://github.com/tombuildsstuff/giovanni

**Comment by Xuanwo** [comment]
Hi, we are building an application-oriented unified storage layer for Golang called [go-storage](https://github.com/aos-dev/go-storage). With the help of go-storage, we can have native support for azblob, gcs (like https://github.com/benbjohnson/litestream/issues/69) and more services as described in https://github.com/aos-dev/go-storage/issues/536.

Please take a look and leave comments to us, we will prioritize the needs that come from you!
