### ISSUE TITLE
Refactor Replica

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#135]
Currently, the `file` and `s3` replicas share a decent amount of logic but differ in some important implementation details. This could be improved to consolidate common functionality into a concrete `Replica` type and move platform-specific functionality into a `ReplicaClient` interface.

This refactor also needs to support both push and pull models for the upcoming `http` replica type. Once this refactor is complete, a native Azure Blob Storage implementation can be added.

**Comment by yanc0** [comment]
Great enhancement here ! I think the GCS can be part of the refactoring to. The S3 compatibility mode provided by Google is really scary. https://github.com/benbjohnson/litestream/issues/74

**Comment by benbjohnson** [comment]
@yanc0 Yes, that's a good point. Using the GCS client directly would make a lot more sense after the refactor. 👍
