### ISSUE TITLE
Does litestream support db with custom collations?

### ISSUE THREAD

**Issue by edwinyzh** [benbjohnson/litestream#139]
In our Delphi/Free Pascal community most of us use mORMot which is a HTTP, ORM and database framework that implements server/client architecture based on SQLite. The problem is it uses **custom collations**.

Does litestream safely work with dbs with custom collations?

Thanks!

**Comment by benbjohnson** [comment]
Hi @edwinyzh. Litestream replicates at the page level so it shouldn't matter if you're using custom collations. Ultimately, Litestream just copies out raw bytes so you should be good to go. 👍
