### ISSUE TITLE
Add support for Raspberry Pi (armhf)

### ISSUE THREAD

**Issue by adamstac** [benbjohnson/litestream#144]
Hey Ben!

I'm planning to use Litestream on a Raspberry Pi 4 Model B on my local network that runs [Gogs](https://gogs.io) via Docker with a SQLite database.

I get the following upon attempted installation, so I guess the Debian package architecture needs to support `armhf` too.

```
pi@Pi-max [10:55:18 PM] [~]
~> % sudo dpkg -i litestream-v0.3.3-linux-amd64.deb                                                           
dpkg: error processing archive litestream-v0.3.3-linux-amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 litestream-v0.3.3-linux-amd64.deb
```

Please consider this feature for all the Raspberry Pi users out there who want to use Litestream.

**Comment by benbjohnson** [comment]
hey Adam! I have some issues (#43 & #57) for getting ARM builds working. There should be release builds ready with the next release. 🎉

**Comment by adamstac** [comment]
Awesome to hear!

**Comment by benbjohnson** [comment]
hey Adam, I have ARM release builds merged into `master` and I cut an alpha release: https://github.com/benbjohnson/litestream/releases/tag/v0.3.4-alpha11

For `armhf`, you should be able to use the 32-bit ARM build (`arm`): https://github.com/benbjohnson/litestream/releases/download/v0.3.4-alpha11/litestream-v0.3.4-alpha11-linux-arm.deb

There's a lot of alphas right now as I can't find a better way of debugging the GitHub Actions with release events. :)

**Comment by benbjohnson** [comment]
Also, I was able to run `litestream` on a 64-bit ARM with an AWS Gravitron instance but I don't have a Raspberry Pi. I need to order one for testing. If you have time, I'd be curious to know how it works for you.
