### ISSUE TITLE
Potential solution for informing people about contributing

### ISSUE THREAD

**Issue by elreydetoda** [benbjohnson/litestream#145]
So, I was listening to your podcast episode on [the changelog](https://changelog.com/podcast/433), and from your discussion, it seems like you are still trying to figure out a way to help people understand your [contribution policy](https://github.com/benbjohnson/litestream/blob/bb146e2c09e69558de71fcd861cf5e3c276a3c02/.github/CONTRIBUTING.md).

I recently ran across something that might help and be a potential solution for not allowing PRs and informing people about your policy. So, I recently submitted [an issue](https://github.com/github/securitylab/issues/328) to a GH repo, and I couldn't choose a blank template. I saw in their [config](https://github.com/github/securitylab/blob/a2d1572ddcd788d984ecf16a5d561a713aa540d1/.github/ISSUE_TEMPLATE/config.yml#L1) that they had disabled it.

So, my idea is you could potentially just have one pr template that would link out to either a blog post or the changelog episode so people can understand why you don't want to accept PRs, and then you turn off the blank template. Then people shouldn't be able to create a PR against the repo.

Another link you could make is out to the docs for this project since you mention they are MIT license and you welcome contributions there.

**Comment by benbjohnson** [comment]
hey @elreydetoda, sorry for the late reply. That sounds like a brilliant idea, but unfortunately, I tried it and it doesn't look like `.github/PULL_REQUEST_TEMPLATE` supports a `config.yml` file. 

I added a `.github/pull_request_template.md` to the repo with the README link and the docs repo link. Thanks!
