### ISSUE TITLE
Would it be possible to create an OpenBSD binary with each new release of litestream?

### ISSUE THREAD

**Issue by netstx** [benbjohnson/litestream#150]
I am not too familiar with how cross-compilation works in this case, but I am wondering if it'd be too much work?

If a build VM is needed then I am willing to provide one :)

**Comment by benbjohnson** [comment]
@netstx I tried to look at cross-compiling but I could find much on cross-compiling to OpenBSD with CGO. I also tried running an OpenBSD cloud VPS on Vultr but I'm honestly not familiar enough with OpenBSD so it was taking me quite a while to not even get very far with it. :)

I'm open having release builds for OpenBSD but I'll need to push it off until I have the time to really dig into it and figure it out.

**Comment by netstx** [comment]
Thanks @benbjohnson. Just out of curiosity, if you chose not to use cgo for cross-compilation, would you consider automating the build on OpenBSD using GitHub Webhooks?

OpenBSD has a package called "snare", it's a service that will listen for HTTP requests from GitHub Webhook (can be HTTPS if behind a reverse proxy, "relayd" is part of the OpenBSD base and can be used for that purpose). 

Snare can be configured in just a few lines so that when certain conditions are met (like any "push" events on benbjohnson/litestream), it will run a command (a shell script for example) to clone repo, build with go, then scp it to another host for example, or push it to the httpd chroot directory so you can download it from the machine itself.

I was going to play around with snare anyways to auto build my Hugo site, but I could also test it with litestream if you think that could add value to the project down the road.

If/when the time comes, please let me know and I'd be willing to help :)

**Comment by jungle-boogie** [comment]
Thanks to @netstx for opening this issue and for the request for OpenBSD builds.

@benbjohnson, 

OpenBSD is actually pretty easy to use and has low maintenance requirements, so I don't think it will get in your way when you're ready to make the builds. 

Let us know how we can help you out!

Thanks,
j.b.

**Comment by netstx** [comment]
@jungle-boogie Howdy! Would you be interested in testing Go builds on OpenBSD 6.9 using snare? If we can get some of the testing out of the way it might make it easier for Ben to include it in his project.

**Comment by jungle-boogie** [comment]
Hey @netstx,

Sure, I can setup an OpenBSD VM on vultr. But I don't know where to find info on `snare`. 
Can you share a link to the project page or some place else?

I imagine I would just need to fork Ben's litestream repo and add a new workflow file in my repo for snare than to make the build?

Thanks!

**Comment by jungle-boogie** [comment]
Here's the page:
https://tratt.net/laurie/src/snare/

**Comment by netstx** [comment]
@jungle-boogie you can install via "pkg_add snare", if you upgrade to 6.9 (unless Vultr is on 6.9 already) then snare will be on the latest version.

The way I was planning is to configure snare, add the webhook to your fork, then the script that snare will execute would build the go binary (so Go must be setup on your OpenBSD VM already).

**Comment by netstx** [comment]
> 
> 
> Here's the page:
> https://tratt.net/laurie/src/snare/

https://github.com/softdevteam/snare

**Comment by jungle-boogie** [comment]
Progress so far:

- [x] VM Setup
- [x] Upgraded to snapshots, because why not?
- [x] My user account created
- [x] `snare` and `git` installed
- [x] Forked Ben's repo
- [x] Created webhook in my repo
- [x] Built `Litesteam` from src:

```
$ ./go/bin/litestream version
(development build)
```

**Comment by jungle-boogie** [comment]
Guess now I just need to complete the `snare.conf` config and setup some kind of script.

I think for testing, it doesn't need to be too elaborate, right? Just have it update the copy of the repo and `go install ./cmd/litestream`?

**Comment by netstx** [comment]
Yes, something like git clone ..., cd ..., go build, etc. You could then copy/rsync/scp the binary somewhere else afterwards.

**Comment by benbjohnson** [comment]
@netstx @jungle-boogie Thanks for digging into all this. I already build the Windows version & macOS versions with runbooks so I don't mind manually building for OpenBSD. The main issue I had was that I just don't know the ecosystem so figuring out how to install git & Go and all that was more time than I wanted to invest a month ago.

If you can provide steps to go from clean VM to getting Litestream building then I'll add release builds for it. 👍

**Comment by jungle-boogie** [comment]
hi @benbjohnson,

Sure, I can do that. I didn't make any progress with `snare` today, been busy with work.

I'll assume you're using a VM on your computer, but I don't know which OS you're using or what hypervisor so these directions will be kind of general. I'm sure you can fill in the blanks, though, you made `lightstream` after all!

From this page, download the install69.iso file:
https://ftp.openbsd.org/pub/OpenBSD/6.9/amd64/

Also read this page:
https://ftp.openbsd.org/pub/OpenBSD/6.9/amd64/INSTALL.amd64

Put that in your VM. You probably could get by with 512MB of RAM just fine, but feel free to add however much you want.

Boot up the VM and you'll see a `boot>` prompt, After a few seconds, this will start booting the OS and take you to a few options. Choose install and you can answer the next few questions. I'd recommend setting up a user account, so that you don't have to use root for all your build work.

You can change the partition layout if you want. OpenBSD partitions the drive off in many ways, so feel free to adjust as needed.

Near the end of the installer, you will be prompted as to what sets you want to install. The default is all, but you can `-x*` to not install anything related to XWindow, if desired.

Things will install and you'll be prompted to set the time zone and reboot.

You should now be able to eject the ISO file from your hypervisor.

**Comment by jungle-boogie** [comment]
Now that OpenBSD is installed, here's a few things to do after you're logged in, either with the user account or root.

OpenBSD has a `sudo` alternative by default in the base OS, and it's called `doas`. You `doas.conf` file goes in /etc/doas.conf and can look something like this:
```
permit persist :wheel
permit persist keepenv user as root
```
man page for it: http://man.openbsd.org/doas.conf

Installing packages is pretty easy:
`pkg_add git go`

The current versions of those on the release branch are go: 1.16.2 and git: 2.31.1
The latest version of SQLite is available as well, 3.35.5.

OpenBSD doesn't have as many packages as Linux, but there's many things available. 
You can use https://openports.pl to browse/search for something.

Occasionally errata will be released and you can use `syspatch` to get the latest fixes for the OS.

This is pretty much all I did yesterday to build Litestream form source.

Let us know if you have any difficulties!

**Comment by netstx** [comment]
I found the following cross-compile script from another Go project (micro) which I think makes it a lot easier to build it for OpenBSD (and others) rather than doing it separately like we have been talking about: https://github.com/zyedidia/micro/blob/master/tools/cross-compile.sh

**Comment by jungle-boogie** [comment]
Yes, cross compiling is also a solution. Good idea.

**Comment by benbjohnson** [comment]
Litestream has a C dependency and cross-compiling support for CGO is not great.

**Comment by benbjohnson** [comment]
@netstx @jungle-boogie Thanks for all the help on this! I was able to get static & non-static builds made for a pre-release version. I'll make release builds for the next release as well (v0.3.5).

You can find the builds here: https://github.com/benbjohnson/litestream/releases/tag/v0.3.5-alpha.7

**Comment by netstx** [comment]
That's awesome news @benbjohnson, thanks for taking the time to do this!

**Comment by jungle-boogie** [comment]
Thank you, Ben, for working with us on getting OpenBSD builds made.
