### ISSUE TITLE
Add README badge linking to image on DockerHub

### ISSUE THREAD

**Issue by mtlynch** [benbjohnson/litestream#172]
I find it helpful to have a direct link from a project's README to its page on DockerHub. For example, here is LogPaste's

```markdown
[![Docker Pulls](https://img.shields.io/docker/pulls/mtlynch/logpaste.svg?maxAge=604800)](https://hub.docker.com/r/mtlynch/logpaste/)
```

![image](https://user-images.githubusercontent.com/7783288/115802833-a05c3800-a3ad-11eb-85e3-53cfb02f48f0.png)

**Comment by benbjohnson** [comment]
That's a great idea, thanks @mtlynch. I pushed the change up here: https://github.com/benbjohnson/litestream/commit/6acfbcbc64dbb0bbc9fee492d2ec804423de14ef
