### ISSUE TITLE
SQLcipher support

### ISSUE THREAD

**Issue by mig5** [benbjohnson/litestream#177]
Hi,

Thanks for your work on Litestream, it looks really interesting.

I have a use case whereby my SQLite databases are encrypted using SQLCipher: https://www.zetetic.net/sqlcipher/

I have not yet tried Litestream but at a glance I am guessing I could not use it since the SQLite databases are encrypted and would need to be 'decrypted' first in order to access the WAL. SQLcipher supports WAL: https://www.zetetic.net/sqlcipher/design/

> Write Ahead Log Files - Using the new WAL mode (i.e. PRAGMA journal_mode = WAL;), page data stored in the WAL file is encrypted using the database key. Pages in the rollback journal are encrypted using the same key as the main database. Verification: create an encrypted database, start a transaction, make changes, and then inspect the -wal file using hexdump or a similar program. 

It would be amazing if Litestream could support SQLcipher somehow, eventually.

As an unrelated note, I too have potentially thousands of SQLite databases so would benefit from https://github.com/benbjohnson/litestream/issues/42 but I wonder how it would really scale if it is per process. Keeping an eye on your project nonetheless :)

**Comment by benbjohnson** [comment]
Thanks for submitting the issue, @mig5. Litestream treats the database & WAL page data as opaque so it might work with SQLCipher. It mainly uses the WAL header & WAL frame headers to verify checksums for integrity and end-of-transaction boundaries. However, I may be able to make it work without those verification pieces.

I'll have to play around with it and see what would work. I'd like to avoid embedding SQLCipher into Litestream though. That seems like it could be overly complicated.

Regarding #42, Litestream is just a single process so it should scale pretty well. There's just a small bit of metadata for each database to maintain a position. Litestream currently polls to check for new data but I'm updating that to use [fsnotify](https://github.com/fsnotify/fsnotify) so it should scale pretty well.

**Comment by patte** [comment]
Unfortunately litestream in combination with [SQLCipher](https://www.zetetic.net/sqlcipher/) does not just work.

```
$ ./sqlcipher fruits.db
PRAGMA key = 'passphrase';
CREATE TABLE fruits (name TEXT, color TEXT);
INSERT INTO fruits (name, color) VALUES ('apple', 'red');
INSERT INTO fruits (name, color) VALUES ('banana', 'yellow');

$ litestream replicate fruits.db s3://sqlbucket.localhost:9000/fruits.db
litestream v0.3.4
initialized db: /project/sqlcipher/fruits.db
replicating to: name="s3" type="s3" bucket="sqlbucket" path="fruits.db" region="us-east-1" endpoint="http://localhost:9000" sync-interval=1s
/project/sqlcipher/fruits.db: sync error: file is not a database

$ hexdump -C fruits.db
00000000  17 91 6c 65 cd cd ef e6  fc fb c8 ce 2b b5 4f 84  |..le........+.O.|
00000010  e6 e5 f0 c9 bf 76 1b 1a  82 d9 1c d7 f0 90 8e 51  |.....v.........Q|
00000020  b2 29 a3 ac ed 88 04 e9  a7 11 85 c6 23 43 db a8  |.)..........#C..|
00000030  2a 4d f7 2f 13 38 eb 66  33 6e b5 73 b7 ab 5d 06  |*M./.8.f3n.s..].|
00000040  30 71 ab 3c a2 1c 66 b1  6a ef 83 c6 a8 2e ef a9  |0q.<..f.j.......|
00000050  6d 0d 45 fa 07 e6 51 37  a8 b8 63 93 58 94 af 73  |m.E...Q7..c.X..s|
00000060  d2 a8 1e 45 ee 3d d0 0b  00 b8 b0 58 1c bc bf 4f  |...E.=.....X...O|
00000070  84 cd 4a dd 21 47 67 ee  6d 99 5a cc a7 e0 db 14  |..J.!Gg.m.Z.....|
00000080  45 85 4d dd e8 ff 95 f4  fb a5 a3 79 36 65 b7 b4  |E.M........y6e..|
00000090  eb 38 ee 96 50 4a 84 74  01 72 de 4e b6 fd fe 40  |.8..PJ.t.r.N...@|
000000a0  09 36 21 b7 8f bb b6 26  d9 36 89 3d b7 49 db 10  |.6!....&.6.=.I..|
000000b0  87 d0 20 85 f6 4b b2 2f  73 bf e5 63 6c 83 cb ef  |.. ..K./s..cl...|
000000c0  f7 0e b0 85 5e 99 5c 29  52 2e 38 e5 20 48 f1 e3  |....^.\)R.8. H..|
shortened
```
(my setup works perfectly with an unencrypted db)

**Comment by benbjohnson** [comment]
Thanks for trying it out. I suspected it wouldn’t work as I think I’d probably need to compile in a different version of SQLite that has the SQLCipher changes in it.

**Comment by benbjohnson** [comment]
@morki Good question. No, it's not supported. I marked it as `wontfix`.
