### ISSUE TITLE
Subprocess execution

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#187]
Litestream currently recommends using `s6` for process management when running in a Docker container. However, that's probably overkill for most use cases that simply use `litestream` and one other process.

Adding an `-exec CMD` flag to `litestream replicate` would remove the need to setup `s6` and would allow Litestream to act as a simple process manager. Litestream will exit when the process exits and will forward signals as needed.

The usage would look something like:

```sh
$ litestream replicate -exec "myapp -dsn sqlite3://path/to/db"
```

**Comment by chrisfrank** [comment]
Litestream is such an exciting project. I've been following its development with interest.

I wanted join the discussion here to (a) express that I'd find a simpler alternative to `s6` useful, and (b) ask about whether Heroku's `Procfile` "standard" is common in the Go community? It looks like the author of `go-sqlite3` is also the author of a Go Procfile runner: https://github.com/mattn/goreman

A Procfile for `litestream` would look something like...
```
replicate: litestream replicate
serve: ./myapp
```

...and the accompanying Dockerfile would, I guess, invoke `goreman start` as its entrypoint.

(I'm not necessarily suggesting this _instead of_ a built-in process manager, but I'd be happy to document a Procfile-based setup if it would be useful until a built-in process manager exists.)

**Comment by benbjohnson** [comment]
hey Chris, thanks for the feedback. I've used Procfiles way back when I was writing Rails apps but I haven't seen them used much in Go. I hadn't considered using them for Litestream because IIRC Heroku splits out each type into its own dyno but if you're running with foreman/goreman then it should all be on the same host so that should work.

Do you know if foreman/goreman support the `release` type? It seems like you'd need an initialization script to restore the database if it doesn't exist and a replica exists. Something similar to this code: https://github.com/benbjohnson/litestream-s6-example/blob/main/etc/cont-init.d/00-litestream#L5-L11

**Comment by chrisfrank** [comment]
>  It seems like you'd need an initialization script to restore the database if it doesn't exist and a replica exists.

Great point, I think we would need an init script for that case. At least until #121 lands, if I've understood that issue correctly?

Foreman will happily run whatever processes the Procfile declares, but I think the constraints are that (a) there's no way to declare one process as dependent on another, and (b) when _any_ of its child processes exit, Foreman sends `SIGTERM` to all its other processes, waits for a clean shutdown, and then exits itself. Given those constraints, a Litestream Procfile would need to be something like...

```
db: ./init_db.sh
server: ./myapp
```
... where `init_db.sh` is a shell script like the one you [linked to](https://github.com/benbjohnson/litestream-s6-example/blob/main/etc/cont-init.d/00-litestream#L5-L11), modified to run `litestream replicate` after it has completed the restoration check.

**Comment by chrisfrank** [comment]
That was fast :)

Congratulations, the subprocess execution that landed this week looks fantastic. 🚀

**Comment by benbjohnson** [comment]
Thanks! It really came together easier than I expected. I added an example with it in Docker on this repo as well if you’re interested: https://github.com/benbjohnson/litestream-docker-example
