### ISSUE TITLE
Reduce default S3 sync interval

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#189]
The `s3` replica has an odd default sync interval for historical reasons. Originally, it was set to 10 seconds to reduce cost, however, this was a poor experience when users were first trying Litestream so it was changed to 1 second but only if the user replicated using command line args (aka not a config).

Litestream only replicates when database changes have occurred though so costs are very low in practice. For example, Michael Lynch wrote [a blog post](https://mtlynch.io/litestream/) about how he only spent $0.03 per month on S3 charges for Litestream. In light of this, it makes sense to just default the sync interval for the S3 replica to 1 second in all cases. At most, this should cost $13 per month but only if there are continuous writes to the database. Users can adjust their sync interval in the config file as needed.

**Comment by theronic** [comment]
Litestream seems to be syncing to S3 every second even though nothing is writing to the database.
![image](https://user-images.githubusercontent.com/1011676/173858827-26835db8-ec0f-4fe0-90dd-a9ac71e3c65b.png)
