### ISSUE TITLE
Ubuntu 18.04 support (`GLIBC_2.28` issue)

### ISSUE THREAD

**Issue by jloh** [benbjohnson/litestream#198]
Hi all, thanks for the awesome little tool!

I installed the deb recently on Ubuntu 18.04 but unfortunately it doesn't seem to run complaining about `libc` issues:

```
root@main:~# litestream version
litestream: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by litestream)
root@main:~#
```

Any idea if this is possible to fix or is 18.04 to old to run the tool?

**Comment by benbjohnson** [comment]
Hi @jloh, thanks for reporting that bug. I switched the release build to use Ubuntu 18.04 so future versions will work on Ubuntu 18.04 & 20.04. In the meantime, you can run the static release builds for v0.3.4 on Ubuntu 18.04.

**Comment by jloh** [comment]
Thanks @benbjohnson! I didn't check releases properly and realise there was a statically linked version. Replacing the installed version with that worked perfect 👍
