### ISSUE TITLE
Project description should maybe be changed from S3 to blob

### ISSUE THREAD

**Issue by simongottschlag** [benbjohnson/litestream#205]
Hi!

Notices that when I searched for this project just now the description says S3. Maybe it should be updated to blob to reflect the latest changes? 😊👍

**Comment by benbjohnson** [comment]
Hey! Yeah, that's a good point. Litestream also supports file-based and sftp-based replication so it's even more than just blob storage. I want to keep it short and easy to understand though—I'll have to think about it.

**Comment by simongottschlag** [comment]
😁👍

I suggest just removing S3 to begin with: Streaming replication for SQLite.

**Comment by benbjohnson** [comment]
That's a good start. Updated! :)
