### ISSUE TITLE
Documentation on using litestream as a library in a Go project

### ISSUE THREAD

**Issue by Koeng101** [benbjohnson/litestream#215]
I'm looking at embedding litestream into another Go project I have running, but found that there aren't any docs on how to use litestream within a different Go project. It would be much appreciated if there was a simple example of how to use litestream as a library. Thanks!

**Comment by benbjohnson** [comment]
It is possible to use Litestream as a library but since it’s not v1.0.0 yet, the API doesn’t have any stability guarantees so we don’t publicize it very much. You can find an example repo here though: https://github.com/benbjohnson/litestream-library-example

**Comment by janflyborg** [comment]
I know this ticket has been closed, but any updates on this? Specifically, I'm thinking about having one SQLite database for each user in my system, and it would be cumbersome (and not verify efficient) to start one Litestream process for each database, so is the API stable enough for such usage now?

**Comment by benbjohnson** [comment]
@janflyborg I provided that `litestream-library-example` repo, but after further use I've found that there's an issue with it on macOS. The lock system in macOS doesn't allow for per file descriptor locks so there can be issues with adding and removing SQLite databases under management with Litestream on that OS. Not sure if it applies to you but it's a bit sticky if it does.

For your use case, there is ticket #42 scheduled for the `v0.4.0` release where it will be able to replicate entire directories so you can have multiple databases managed without setup a separate process for each. However, Litestream uses a polling mechanism currently that can be really slow if you have a lot of databases. That's also being fixed via #190.

**Comment by janflyborg** [comment]
Thanks for the answer. That was exactly what I was looking for. 

Let me tell you that I really appreciate your work. Our company has been a long time user of Bolt, but switched to SQLite a few years back. This initiative (Litestream) is really covering new ground, and your effort it is highly appreciated.

**Comment by benbjohnson** [comment]
Thanks, @janflyborg! I appreciate it. That means a lot to hear.

**Comment by lherman-cs** [comment]
@Koeng101 @janflyborg https://github.com/benbjohnson/litestream/pull/608 might fulfill your needs, please feel free to scrutinize the change.
