### ISSUE TITLE
Inequalities seem misused

### ISSUE THREAD

**Issue by TomMD** [benbjohnson/litestream#226]
Perhaps there's a common idiom in Go, but it seems like there are some misused inequalities such as:

https://github.com/benbjohnson/litestream/blob/fc897b481fae32be0b3a6e61e64b221a0df89cc5/replica.go#L1193

Which would lead to improper operation.  The bug was found by staticcheck in a [one-off run of Lift](https://lift.sonatype.com/result/TomMD/litestream/01FAGVN1VE650Q9228741QWTVR?t=CustomTool%20%22Staticcheck%22%7CSA4000).

**Comment by benbjohnson** [comment]
No, you're right. That's just a straight-up bug. Restoring by a specific index is uncommon which is why that snuck by for so long. Thanks for reporting the issue! I'll get it fixed up.

**Comment by benbjohnson** [comment]
I added a ticket for running `staticcheck` on CI as well. https://github.com/benbjohnson/litestream/issues/227

**Comment by hifi** [comment]
I believe these have been caught by now by staticcheck.
