### ISSUE TITLE
Integrate staticcheck into build system

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#227]
Some basic static analysis should be added to the CI system. Staticcheck is a good start. 

See also: https://github.com/benbjohnson/litestream/issues/226

**Comment by TomMD** [comment]
You might also want GoSec and Semgrep ([ex](https://lift.sonatype.com/result/TomMD/litestream/01FAGVN1VE650Q9228741QWTVR?t=CustomTool%20%22Semgrep%22%7Copt.semgrep.eqeq-is-bad&t=CustomTool%20%22GoSec%22%7CG601&t=CustomTool%20%22GoSec%22%7CG307)).

As a founder of what became the above-linked tool I'm going to plug that you could just install the tool free for open source on your repository via github apps. It saves the pain of numerous actions integrations and will result in pull request review comments so users don't need to look at the full list of issues, most of which seem to be less interesting and not worth acting on.
