### ISSUE TITLE
Is there compaction? If yes, please document.

### ISSUE THREAD

**Issue by tv42** [benbjohnson/litestream#231]
> By default, Litestream will replicate new changes to an S3 replica every 10 seconds. This can be reasonably configured down to 1 second with the sync-timeout configuration setting.

https://litestream.io/tips/#data-loss-window

Are all those objects forever, or is there a compaction/pruning mechanism?
I couldn't find an answer on the doc site.

https://github.com/benbjohnson/litestream/blob/ac32e8e089f155d2e06637ca6b140ecb231e1d90/replica.go#L499-L501
seems to hint that they are, but then `DefaultRetention` of 24 hours seems too low for it to mean that? https://github.com/benbjohnson/litestream/blob/77274abf81fc878fff4445c6306b9da3354b6960/replica.go#L27

Minio naively stores 1 bucket == 1 directory and slows down a *lot* with large directories.

AWS S3 (in many configurations) bills by minimum object size of 128 kB, sometimes it adds a 32 kB per-object overhead, etc.

**Comment by tv42** [comment]
It seems https://litestream.io/reference/generations/#example is how it works. Every now and then, litestream starts with a "clean slate" generation that is a full backup, and then prunes generations older than the (default 24h) threshold.

**Comment by tv42** [comment]
Also this: 

> If Litestream detects that there is a break in the WAL frames then it will automatically start a new generation with a new random hex string and a snapshot. This ensures we always have a contiguous set of files to replay even if Litestream is stopped and misses WAL frames being written.

https://litestream.io/how-it-works/#snapshots--generations

And this:

https://litestream.io/reference/config/#retention-period

So there is a bunch of stuff, just... I didn't end up discovering it? A mention of this belongs on the How it works page, which is where I went to understand the system.

**Comment by benbjohnson** [comment]
hey @tv42! Long time! Sorry for the late response. Thanks for digging into the docs. I wrote up a section on retention in the _How it works_ page. Let me know if this sounds good or if it could use some more info: https://github.com/benbjohnson/litestream.io/pull/35

**Comment by tv42** [comment]
<3 Appreciate the effort, I think I'll be using Litestream for my next project. I wrote some comments on the pull request.

**Comment by benbjohnson** [comment]
@tv42 I don't see any comments on the pull request. Did you submit the review? Also, let me know how Litestream goes for you.

**Comment by benbjohnson** [comment]
@tv42 I went ahead and merged the docs PR. Feel free to post the comments here instead. Thanks!
