### ISSUE TITLE
A RESTART checkpoint during a snapshot transfer locks the database for writing until the snapshot has finished

### ISSUE THREAD

**Issue by t-voet** [benbjohnson/litestream#237]
Litestream v0.3.5 and a 25 GB database on ZFS with 64k page_size. A SFTP snapshot takes hours, during which the WAL hits 10k pages (640 MB). An obvious solution could be skipping RESTART checkpoints while a snapshot transfer is in progress.

**Comment by t-voet** [comment]
You're the best. If you send me your public key, I can provide a high-speed (2.5 Gbps) SFTP account for testing.

**Comment by hifi** [comment]
As I believe #477 fixed this I'll close. Thanks.
