### ISSUE TITLE
Prometheus metrics cannot be enabled via command line flag

### ISSUE THREAD

**Issue by atheriel** [benbjohnson/litestream#243]
Most of Litestream's configuration can be passed as command-line arguments instead of using a config file, with the notable exception of Prometheus metrics.

Can I suggest adding a `-metrics-addr` flag to the replicate command for this? It would be convenient for simple setups to be able to do so.

**Comment by benbjohnson** [comment]
@atheriel Yes, that seems reasonable. I'll probably change the flag to `-addr` as the HTTP server will also be used for an HTTP replication implementation coming in `v0.4.0`.
