### ISSUE TITLE
Write Docker guide

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#28]
Litestream should already work inside Docker but testing & documentation are needed.

**Comment by cablespaghetti** [comment]
Is the plan with Docker support to keep this repository dedicated to building the code and have users build their container images?

I might have a go at building a nice multi-arch, [distroless](https://github.com/GoogleContainerTools/distroless), rootless image if that’s the case.

**Comment by benbjohnson** [comment]
Hi Sam, I actually have `Dockerfile` working on the `docker` branch that uses a distroless image that @philips recommended: https://github.com/benbjohnson/litestream/blob/docker/Dockerfile

I've only done a little testing on it so far though.

**Comment by cablespaghetti** [comment]
Looks good! I'll have a test with that.

If you use Docker Buildx with that you should get multi-arch images with little-to-no effort.

https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by mtlynch** [comment]
In case it's helpful, I'm using litestream in a [small web app](https://logs.tinypilotkvm.com).

It installs litestream [in the Dockerfile](https://github.com/mtlynch/logpaste/blob/1fcb8e28677b611e51a57c621e5be904e3c0ff5f/Dockerfile), and then in the [entrypoint](https://github.com/mtlynch/logpaste/blob/1fcb8e28677b611e51a57c621e5be904e3c0ff5f/docker_entrypoint), it uses litestream to pull down the latest version of the DB, then it starts replicating in the background.

It's a little against Docker conventions to run two services in the same container, but it's super handy to be able to deploy the single image anywhere and have it pull down the data and start replicating.

**Comment by benbjohnson** [comment]
Thanks, @mtlynch. That's a great setup you have. I've been playing around with running Litestream as a separate Docker container but I like how you can run a single Docker container with both the app and Litestream.

I didn't realize it was even possible to run systemd inside Docker. That would be pretty awesome since it would handle restarts if anything went wrong.

I noticed the [restore command](https://github.com/mtlynch/logpaste/blob/1fcb8e28677b611e51a57c621e5be904e3c0ff5f/docker_entrypoint#L27-L30) you call if the DB doesn't exist. Would it be easier to just have a flag on restore to ignore if the file already exists?

**Comment by mtlynch** [comment]
>I didn't realize it was even possible to run systemd inside Docker. That would be pretty awesome since it would handle restarts if anything went wrong.

Oh, I'm not running systemd. I tried that initially and realized it didn't work under Docker. It's just a regular background process by suffixing the command with `&`.

>I noticed the restore command you call if the DB doesn't exist. Would it be easier to just have a flag on restore to ignore if the file already exists?

The way I'm using it is actually the opposite. I always launch the Docker image on a container with no volume mounted, so the DB can't exist at that point in the script.

The check is for whether it should allow the app to create a new DB from scratch or to pull down an existing DB from S3. The idea is that the first time you run, you'd do this:

```bash
docker run \
  -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
  -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
  -e "AWS_REGION=${AWS_REGION}" \
  -e "DB_REPLICA_URL=${DB_REPLICA_URL}" \
  -e "CREATE_NEW_DB='true'" `# change to false after first run` \
  --name logpaste \
  mtlynch/logpaste
```

So then you'd bootstrap the DB, then all subsequent runs you'd leave out the `CREATE_NEW_DB` environment variable.

But I'm not crazy about that behavior because it probably causes bad things to happen if you forget to take out the `CREATE_NEW_DB` variable on the second run. I'm guessing bad things happen if you create a new DB, write some data, then create a separate DB and replicate to the same S3 location.

The other option I considered was to just ignore failure on the initial restore command, but then I'd still have the possibility of creating a second fresh database on some litestream transient failure.

I guess if I were to request a fix at the litestream level, it would be to have a restore flag that's like:

```bash
litestream restore --ok-if-no-replicas-exist /some/path.db
```

And the behavior of `--ok-if-no-replicas-exist` (with a less stupid name) would be that if litestream queries the S3 bucket and finds no replicas, it would just create an empty sqlite database instead.

**Comment by cablespaghetti** [comment]
I've built a multi-arch image from the `docker` branch and pushed it here, if anyone else is also trying this kind of thing: https://hub.docker.com/r/cablespaghetti/litestream/tags?page=1&ordering=last_updated

Just seeing if I can get it to work nicely as a "sidecar" in Kubernetes. :)

**Comment by polyrand** [comment]
I've been thinking a bit about how I could run litestream inside a separate container. Running it as @mtlynch did is an option, but then the litestream process would not handle signals properly.

My thinking was doing something like:

```Dockerfile
version: '3.8'

services:
  app:
    image: ....
    volumes:
      - databases:/home/nonrootuser/dbs

  litestream:
    image: litestream:latest
    init: true
    restart: always
    volumes:
      - databases:/dbs
    healthcheck:
      test: litestream generations /dbs | awk '{ print $3 }' | check_lag_time # + whatever is needed
      retries: 2



volumes:
  databases:
    driver_opts:
      type: none
      device: /root/dbs  # <- local folder where sqlite DBs are stored
      o: bind
```

With that, you can get litestream as a separate service, so it handles signals properly. And you can have a healthcheck to make sure it's working.

I think it would also be better to manage the DBs by `exec`'ing stuff inside the litestream service/container.

**Comment by cablespaghetti** [comment]
Good shout on the the health check, I'll add that to my Kubernetes example: https://github.com/cablespaghetti/litestream.io/blob/7405fb57c5cdd67c580f2fbbac8a5c9c1cd50532/content/guides/kubernetes-statefulset/yaml/wordpress-statefulset.yaml#L26

This is very similar to how my above config works and yes I think separate container, same volume is the way to go. :+1:

**Comment by polyrand** [comment]
Looks great! I don't know if there are any docker-compose guides being written, but that's something I can write.

**Comment by kurtis-poole** [comment]
Would be great to have Litestream running as an additional process in a container with a Go process too, for when can't share storage between containers (Fly!).

I had partial success getting them running in one Dockerfile using Overmind. Replicate doesn't seem to work after the initial run. I swapped in modernc.org/sqlite because CGO, perhaps this is why. The tests pass. I note static build on your to-do and this would be useful.

https://github.com/kurtis-poole/go-fly-lite/blob/main/Dockerfile

I love the idea of a single container with Litestream that restores from object storage on start, and replicates on further updates. Can you avoid any persistent storage for the container if its being restored + replicated? This would be good.

**Comment by mtlynch** [comment]
>Would be great to have Litestream running as an additional process in a container with a Go process too, for when can't share storage between containers (Fly!).

@kurtis-poole - I have a working implementation of this. It's a golang web service that requires no persistent storage across container runs. I've been using it in production for the past month, and it's working great.

* [Source](https://github.com/mtlynch/logpaste)
* [My Docker entrypoint script](https://github.com/mtlynch/logpaste/blob/118e21588a46d14d1c179c91d68574e57b834554/docker_entrypoint)
* [Docker + LiteStream Quick Start](https://github.com/mtlynch/logpaste#from-docker--cloud-data-replication)

**Comment by kurtis-poole** [comment]
> > Would be great to have Litestream running as an additional process in a container with a Go process too, for when can't share storage between containers (Fly!).
> 
> @kurtis-poole - I have a working implementation of this. It's a golang web service that requires no persistent storage across container runs. I've been using it in production for the past month, and it's working great.
> 
> * [Source](https://github.com/mtlynch/logpaste)
> * [My Docker entrypoint script](https://github.com/mtlynch/logpaste/blob/118e21588a46d14d1c179c91d68574e57b834554/docker_entrypoint)
> * [Docker + LiteStream Quick Start](https://github.com/mtlynch/logpaste#from-docker--cloud-data-replication)

Thanks! I'd spotted your first revision. I think that stack is great, and your project is good inspiration. Great to hear it works!

Overmind gives you some process management and fancy logs, but I think I've got sidetracked. Whilst Overmind seems pretty simple, it's another little bit of complexity. I'd like to keep it as straightforward as possible. I'll revisit your entrypoint script.

**Comment by benbjohnson** [comment]
Thanks for everyone's contributions. I wrote up a Docker guide for running Litestream as a separate container and for running Litestream in the same container (using [s6](https://github.com/just-containers/s6-overlay)). @mtlynch's original Docker implementation was a big help with getting started.

I eventually opted for s6 because it's pretty small and written in C. Overmind seems to have more layers as it uses tmux.

There's now an official Docker image that you find here: https://hub.docker.com/r/litestream/litestream

There's also a repo for the s6-based bundling of Litestream that you can find here: https://github.com/benbjohnson/litestream-s6-example

I'd love to hear feedback if anyone gets a chance to take a peek. Thanks!

**Comment by kurtis-poole** [comment]
> Thanks for everyone's contributions. I wrote up a Docker guide for running Litestream as a separate container and for running Litestream in the same container (using [s6](https://github.com/just-containers/s6-overlay)). @mtlynch's original Docker implementation was a big help with getting started.
> 
> I eventually opted for s6 because it's pretty small and written in C. Overmind seems to have more layers as it uses tmux.
> 
> There's now an official Docker image that you find here: https://hub.docker.com/r/litestream/litestream
> 
> There's also a repo for the s6-based bundling of Litestream that you can find here: https://github.com/benbjohnson/litestream-s6-example
> 
> I'd love to hear feedback if anyone gets a chance to take a peek. Thanks!

Thanks for your work on this. The example project is clear and I've refactored one of my projects following it. AlI works as intended. I do miss the simplicity of a simple bash entrypoint with Litestream as a background '&' but like that this is more robust. It becomes more of a chonker of an image but still reasonable (~80mb).

--restore-if-replica is *great*. I'm trying to avoid any persistent storage and being able to recreate from s3 on container start is tidy.

**Comment by benbjohnson** [comment]
> It becomes more of a chonker of an image but still reasonable

Yeah, I'd like to bring that down for sure. I added `gettext` to use `envsubst` which adds some overhead but I think I'm going to add variable expansion directly into Litestream so it's not needed.

**Comment by benbjohnson** [comment]
This was discussed on the Slack but I'll post here too. I was able to drop the total size of Litestream + app + s6-overlay to about 50MB. I also added variable expansion via https://github.com/benbjohnson/litestream/pull/157

**Comment by benbjohnson** [comment]
Also, I pushed up a Docker guide. There's a `tip` docs site that has the latest changes before it gets merged for the next release. You can find it there: http://tip.litestream.io/guides/docker/

**Comment by mtlynch** [comment]
> I also added variable expansion via #157

Oooh, awesome! A great feature I didn't realize I wanted until now.

**Comment by benbjohnson** [comment]
> Oooh, awesome! A great feature I didn't realize I wanted until now.

That's how I felt until I actually implemented it. It's super handy to be able to just pass `-e REPLICA_URL:<VALUE>` to a Docker image and have it replicate somewhere else.
