### ISSUE TITLE
Host fails to parse for non-localhost sites

### ISSUE THREAD

**Issue by tyre** [benbjohnson/litestream#281]
I have a server on my local network running minio and I'd like to use that as my backup destination. Let's say the bucket's name is `pantry`, the server's DNS record is `safe-house`, and the database is `donuts.db`.

On my laptop I run:

```
> litestream replicate /tmp/donuts.db s3://pantry.safe-house:9000/donuts.db
litestream v0.3.7
initialized db: /tmp/donuts.db
replicating to: name="s3" type="s3" bucket="pantry.safe-house" path="donuts.db" region="" endpoint="" sync-interval=1s
```

Uh oh. What follows is a stream of:

```
/tmp/donuts.db(s3): monitor error: cannot lookup bucket region: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
	status code: 403, request id: 9EJREJRVBQ8M7T4S, host id: G1M+U2QDEaikT6MV+4Fl6TI07FPciKAGEAH3fBHwex3wf5cLhH9JyOwWHiMUPRFqa8X0P6jRyzs=
```

It looks like it isn't setting an endpoint. The function that does this is [here](https://github.com/benbjohnson/litestream/blob/fc897b481fae32be0b3a6e61e64b221a0df89cc5/s3/replica_client.go#L672). It's pretty sensible, checking for common domains and setting endpoints that way. But the `else` sets the `bucket` to be the `host` (in this case `"pantry.safe-house"`) and leaves the `endpoint` as `""`. Naturally it is then sad when trying to replicate to nowhere :(

I'm happy to help implement a fix here. What do you think is the best route?

1. In the `else` case, set the `bucket` to be everything before the first `.` and the `endpoint` is everything after that.
2. Something… `else`

**Comment by benbjohnson** [comment]
@tyre Yeah, using the command line URL format with MinIO on another host is currently problematic. The parsing tries to be too clever and it doesn't work well. There's another similar ticket (https://github.com/benbjohnson/litestream/issues/219) so I'll close this as a duplicate.

I think the solution is probably something like what @tv42 mentions in [this comment](https://github.com/benbjohnson/litestream/issues/219#issuecomment-917744623). Don't be too clever and just set the fields via query parameters.
