### ISSUE TITLE
Read configuration file from current directory

### ISSUE THREAD

**Issue by lobre** [benbjohnson/litestream#282]
Hello,

I would propose to have litestream selecting the configuration file `litestream.yml` in the current directory if it exists when `litestream replicate` is used without arguments. Did you already consider that?

And if the file does not exist, it would fall back to the global `/etc/litestream.yml` (or win global path for win).

I feel that it is a good convention to have a `litestream.yml` at the root of the repository, and having to set environment variables or explicitly define flags to reference it complicates the process just a little.

What do you think?

**Comment by deadcoder0904** [comment]
I faced this error while I was trying to use `litestream.yml` in the same file.

```bash
2024/02/27 10:21:26 ERROR failed to run error="config file not found: /etc/litestream.yml"
```

Solved it by using this line in Dockerfile:

```dockerfile
COPY --from=build /app/litestream.yml /etc/litestream.yml
```

Example: https://github.com/benbjohnson/litestream-docker-example/blob/main/Dockerfile & https://github.com/Sh4yy/tiny-stack/blob/main/Dockerfile

@benbjohnson curious if I have to attach `litestream.yml` in volumes as it works fine without it but its recommended at https://litestream.io/guides/docker/

My project -> https://github.com/deadcoder0904/easypanel-nextjs-sqlite/

**Comment by mrityu4** [comment]
For anyone trying this, you can set the LITESTREAM_CONFIG variable to specify a custom path to the litestream.yml file.
