### ISSUE TITLE
Kubernetes guide

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#29]
Add documentation for how to deploy Litestream as a sidecar in a stateful set.

**Comment by cablespaghetti** [comment]
I have read the README and entirely understand your reasons. However are you interested in contributions to documentation?

**Comment by benbjohnson** [comment]
@cablespaghetti Yes! I open sourced the docs repo and it is MIT licensed. https://github.com/benbjohnson/litestream.io

**Comment by beriberikix** [comment]
Very interested in seeing an example of running as a StatefulSet! See #56

**Comment by cablespaghetti** [comment]
Just to reassure you I haven't fallen off the edge of the earth and I have been working on this today. I think I've figured out the "right" was to do it and will try and get a documentation PR over tomorrow!

**Comment by benbjohnson** [comment]
Awesome, thanks @cablespaghetti! I was going to start looking at the Kubernetes stuff this week so that would be a ton of help. 🎉

**Comment by benbjohnson** [comment]
Closed via https://github.com/benbjohnson/litestream.io/pull/28

You can find the deployed version on the development site (`tip`): https://tip.litestream.io/guides/kubernetes/
