### ISSUE TITLE
Snapshot Interval

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#3]
Currently, litestream performs a snapshot when the retention period rolls over but this means that a long retention period can extend restore times. It would be useful to separate the retention interval from the snapshot interval so a user can have multiple snapshots within their retention period (e.g. snapshot every day, keep for one week).

**Comment by jasonbronson** [comment]
It would be useful also to allow the user to backup the db to s3 configuring the snapshot interval times. The realtime is nice but digital ocean’s S3 buckets have rate limits. If I could configure it to take a snapshot every 5 minutes I’d be more then happy with that too.

**Comment by benbjohnson** [comment]
@jasonbronson Are you hitting the DO Spaces rate limits with Litestream? It should default to only 1 `PUT` every 10 seconds and DO rate limits at 150 `PUT`/second. https://www.digitalocean.com/docs/spaces/

**Comment by jasonbronson** [comment]
Is that adjustable in a configuration?

**Comment by benbjohnson** [comment]
Yes, you can set the `sync-interval` for an S3 replica and that will change how often it pushes WAL changes to S3. https://litestream.io/reference/config/#s3-replica

```
dbs:
  - path: /path/to/db
    replicas:
      - url: s3://mybkt/db
        sync-interval: 1s
```

I've tested it as low as 1 second. I believe DO does fixed pricing but if you're using AWS S3 then you get charged per `PUT`. With a `10s` sync interval, it costs about $1.30/month if you have constant writes. With a `1s` sync interval, it costs about $13/month.
