### ISSUE TITLE
Feature : MYSQL driver support

### ISSUE THREAD

**Issue by Thijzer** [benbjohnson/litestream#30]
Not sure if it would fit into the scope of your project, but having MYSQL driver support would be a dream.

**Comment by benbjohnson** [comment]
Hi Thijs. Unfortunately, I think that'd be out of scope for Litestream but [it looks like wal-g has some support for MySQL](https://github.com/wal-g/wal-g/blob/master/MySQL.md) which might be what you're looking for.
