### ISSUE TITLE
Allow 'gs' as Google Cloud Storage replica type string

### ISSUE THREAD

**Issue by febkor** [benbjohnson/litestream#336]
I'm trying to setup LiteStream for Google Cloud Storage.
My config is quite simple

```yaml
dbs:
  - path: /path/to/prod.db
    replicas:
      - url: gs://BUCKET/prod.db
```

Got an error saying `unknown replica type in config: ""`.
Realized that LiteStream currently expects `gcs` (and not `gs`) after looking at the source.

Issues

- GCS seems to officially use `gs` in their URI [(docs)](https://cloud.google.com/bigquery-transfer/docs/cloud-storage-transfer-overview) Should Litestream not support `gs` as well?
- [Config docs](https://litestream.io/reference/config/)  only mention "s3", "abs", "file". The [gcs guide](https://litestream.io/guides/gcs/) does mention it, though it wasn't clear to me that we _had_ to use `gcs`. 
- The error message was not clear.

I'm happy to help with a PR for some of these items (maybe next week).

**Comment by benbjohnson** [comment]
@febkor Yeah, I agree. `gs` seems like a better choice. Litestream is still pre-1.0 so I don't think it's worth trying to support both `gs` & `gcs` for backwards compatibility. If you want to PR up the change to make it `gs` then I'll approve that. 👍

**Comment by jamesnicolas** [comment]
Did this get changed back to gcs? Not sure why it's gcs again instead of gs

**Comment by angusjf** [comment]
@jamesnicolas @benbjohnson looks like the above PR #344 was removed / missing / force pushed over in prod... could it be re-applied?
