### ISSUE TITLE
Stream error after ~1 week of running read replica on v0.4.0-beta.2 

### ISSUE THREAD

**Issue by SebastianSzturo** [benbjohnson/litestream#361]
After a week of running a 0.4 read replica without issue I am seeing following error and a broken database on my replica:

`stream error, retrying: wal segment: invalidate shm file: passive checkpoint: disk I/O error: no such file or directory`

```
# ls
production.sqlite3             production.sqlite3-litestream  production.sqlite3-shm         production.sqlite3-wal
```

Let me know if I can provide any further details or files from this replica.

**Comment by benbjohnson** [comment]
@SebastianSzturo Thanks for opening the issue. I'm looking into it and I'll let you know if I have any questions. 👍

**Comment by benbjohnson** [comment]
I'm closing this issue per the live replication announcement here: https://github.com/benbjohnson/litestream/issues/8#issuecomment-1173214316
