### ISSUE TITLE
Re-implement Windows support

### ISSUE THREAD

**Issue by chakflying** [benbjohnson/litestream#371]
Hi. I'm looking into integrating this in [uptime-kuma](https://github.com/louislam/uptime-kuma/), but currently this does not build on Windows, which is a pretty significant portion of the users. Would be great if this gets officially supported again. Thanks!

Edit: looks like #369 may already fix this, if so you can disregard.

**Comment by benbjohnson** [comment]
Hi @chakflying, issue #369 is just including support for fsnotify (which itself supports Windows). I don't have any immediate plans to re-add Windows support but I'll leave this issue open. It's mostly that I lack the expertise and time to actually have this run well on Windows.

**Comment by gedw99** [comment]
@benbjohnson Assuming the fsnotify is fixed for windows, what are the the other blockers for Windows ? If they can be listed we can get some light / eyeballs on them.

**Comment by benbjohnson** [comment]
There aren't any large technical hurdles for Windows support but the usage numbers for Windows are quite small and I didn't feel comfortable releasing and maintaining the Windows code since CI is not setup to run it. It ended up being a lot of little hassles in order to try to support a small number of users.

**Comment by gedw99** [comment]
thanks @benbjohnson 

i am using litestream on desktops and hoping to use on Windows. But yeah i see your point about lack of users on Windows.

The reason i asked if there are currently well known blockers was only to get an LOE gut instinct for how much of a PITA Windows will be.

**Comment by MMWPF** [comment]
First I wanted to thank @benbjohnson and the community for a useful and great project.
I am working in a small group that develops services on top of windows 10/11/Server.
I find that the project suits our needs.
The only worry that I have is that future versions will not support windows.

I really hope that you will consider returning the windows support (maybe in a lower release rate) so all of us who still use it will be able to enjoy the litestream project

**Comment by gedw99** [comment]
Also am interested in running on windows . Will be happy to help if needed .

**Comment by arjunpola** [comment]
Hi,

I am running Litestream on Windows through source compilation and was able to successfully replicate the db file. 

But, one interesting observation was that when I replicated my DB file from Windows machine to S3, I was only able to restore it on Windows machine but was not able to restore on Mac OS. And same behaviour when I replicate on Mac OS and try to restore it on Windows.

Is this expected or am I missing something? Appreciate any help on this and also not sure if I should be moving this discussion to a different thread.

**Comment by benbjohnson** [comment]
@arjunpola What error are you seeing? I wouldn't expect that restores on a different OS to make a difference.

**Comment by benbjohnson** [comment]
hey everybody, would making Litestream available as a runtime-loadable extension work on the Windows side? I'm not much of a Windows developer and trying to do testing and debugging was difficult and time consuming. Maybe an extension would be an easier approach.

**Comment by arjunpola** [comment]
> @arjunpola What error are you seeing? I wouldn't expect that restores on a different OS to make a difference.

**CONFIG**
```
access-key-id: [AWS_ACCESS_KEY]
secret-access-key: [AWS_SECRET_KEY]

dbs:
  - path: ./db/master.db
    replicas:
      - url: s3://[BUCKET-NAME]/litestream/trial.db
        region: ap-south-1
        sync-interval: 1s
```

**ERROR**
`no matching backups found`

I get the above error when I try to restore on MacBook a database that is backed from Windows. The only thing that changed in the config between the two OS was the path of the DB. Used the following command to restore on Macbook
`litestream restore -o ./trial.db s3://[BUCKET-NAME]/litestream/trial.db`

**Comment by hifi** [comment]
Windows support should work again if built from git. If anyone in this issue could confirm it works fine I'll close this.

It's not supported right now because there's no Windows maintainer but it at least builds for now.

**Comment by arjunpola** [comment]
I am using litestream on windows. Built from source and it works all fine.

**Comment by hifi** [comment]
Thanks for confirming!
