### ISSUE TITLE
Compilation from source on Windows: undefined syscall.Stat_t

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [benbjohnson/litestream#382]
When trying to compile the current version from source on Windows according to instructions from https://litestream.io/install/source/, I get the following error:

# github.com/benbjohnson/litestream/internal
internal\internal.go:184:29: undefined: syscall.Stat_t

**Comment by benbjohnson** [comment]
Hi @serhiy-yevtushenko. Windows support was recently dropped in #299.
