### ISSUE TITLE
stream error, retrying: wal segment: invalidate shm file: passive checkpoint: database disk image is malformed

### ISSUE THREAD

**Issue by ralferoo** [benbjohnson/litestream#383]
I've seen this happen a couple of times, not really sure what causes it, although it might be due to quitting and restarting the copy process.

Before this happened, everything was working fine. I ctrl-C'd the currently running read-only server, and updated my binary, and then relaunched it with this:

ralf@apitest7:~$ litestream replicate -config litestream.replica.yml -exec 'ib-rest -r'

I then modified the RW database on the other server, the change was picked up but the database had been corrupted and was getting sqlite exceptions (caught and returned as a REST error to the client). When I quit the process, it seemed that the database had been corrupted:

...
/home/ralf/words_7.db: wal segment applied: 09b4de9bc51982ab/0000000000000024:0000000000000000
/home/ralf/words_7.db: wal segment applied: 09b4de9bc51982ab/0000000000000024:0000000000000020
/home/ralf/words_7.db: stream error, retrying: wal segment: invalidate shm file: passive checkpoint: database disk image is malformed
...

ralf@apitest7:~$ litestream replicate -config litestream.replica.yml -exec 'ib-rest -r'
litestream 80f8de4d9ed16b7ae6f607bde85d90916784de7d
initialized db: /home/ralf/words_7.db
litestream initialization complete
starting up on port 8080 with 3 threads...
terminate called after throwing an instance of 'SQLite::Exception'
  what():  No row to get a column from. executeStep() was not called, or returned false.
subprocess exited, litestream shutting down
litestream shut down
signal: aborted

ralf@apitest7:~$ sqlite3 words_7.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> select * from card_result order by id desc limit 5;
Error: database disk image is malformed
sqlite>

I have tgz files of both source and corrupted replicated databases and -litestream directories if that's useful for debugging, but I'd rather not share them here.

**Comment by ralferoo** [comment]
Actually, as an extra note, before this happened on the replicated copy, I'd also ctrl-C'd the litestream and app on the source server in order to update my application binary.

I then added more data on the source machine, which replicated to the copy OK, but then I realised I also needed to update the binary for the copy server too in order to expose that data via REST, and when I did so, the database was fine at first, but became corrupted on the next change.

**Comment by benbjohnson** [comment]
Thanks for reporting the bug, @ralferoo. I'm working through refactoring some of the live replication stuff. The issue on restart is that Litestream current plays back from the beginning of the current WAL index in increments and should eventually replay back to the current state but it can have invalid intermediate states that SQLite fails on and it causes the replay to stall and fail.

This is related to https://github.com/benbjohnson/litestream/issues/361 so I'm going close this one out.
