### ISSUE TITLE
SQLITE_FCNTL_PERSIST_WAL maybe not called in every case

### ISSUE THREAD

**Issue by ralferoo** [benbjohnson/litestream#391]
I know you're re-working some of the WAL, but if I helps I think I've tracked down the root cause of when I get errors...

It seems to be that SQLITE_FCNTL_PERSIST_WAL either isn't being set by litestream (I can see it in the code, but not sure if it is being executed) or ignored. There seems to be a race condition that when litestream is syncing, the lock is released temporarily.

While litestream is still running, another process modifies the DB and then pauses before the sync is complete, on exit the DB is OK. If however, it modifies the DB and immediately executes, the WAL file gets removed.

In this case, vmtest9 is a small VM in France, and lxc is a container-based VM far away (in .sg, with a ping of over 230ms, slower is easier to replicate the issue) and they are connected via a wireguard network 192.168.99.1/9:

```
ralf@vmtest9:~$ sqlite3 words_7.db '.backup test.db'
ralf@vmtest9:~$ cat test.primary.yml
addr: ":9090"

dbs:
    - path: /home/ralf/test.db

ralf@lxc:~$ cat test.replica.yml
dbs:
    - path: /home/ralf/test.db
      upstream:
        path: /home/ralf/test.db
        url: http://192.168.99.9:9090


ralf@vmtest9:~$ litestream replicate -config test.primary.yml
litestream 80f8de4d9ed16b7ae6f607bde85d90916784de7d
initialized db: /home/ralf/test.db
http server running at http://localhost:9090
litestream initialization complete
/home/ralf/test.db: init: no wal files available, clearing generation
/home/ralf/test.db: init: no wal files available, clearing generation
/home/ralf/test.db: sync: new generation "72a73404ef700afb", no generation exists

ralf@lxc:~$ litestream replicate -config test.replica.yml
litestream 80f8de4d9ed16b7ae6f607bde85d90916784de7d
initialized db: /home/ralf/test.db
litestream initialization complete
/home/ralf/test.db: snapshot applied

```
(on vmtest9)
```
http: stream generation mismatch, using primary position: client.pos=
http: stream connected: pos=72a73404ef700afb/0000000000000000:0000000000000000 snapshot=true

```
(another window)
```
ralf@vmtest9:~$ ls -ld test*
-rw-r--r-- 1 ralf ralf 61387776 Jun 15 08:59 test.db
drwxr-xr-x 3 ralf ralf     4096 Jun 15 09:00 test.db-litestream
-rw-r--r-- 1 ralf ralf    32768 Jun 15 09:00 test.db-shm
-rw-r--r-- 1 ralf ralf     1080 Jun 15 09:00 test.db-wal
-rw-r--r-- 1 ralf ralf       51 Jun 15 08:57 test.primary.yml

ralf@vmtest9:~$ sqlite3 test.db 'update card_result set batch=batch+1'
ralf@vmtest9:~$ ls -ld test*
-rw-r--r-- 1 ralf ralf 61387776 Jun 15 09:01 test.db
drwxr-xr-x 3 ralf ralf     4096 Jun 15 09:00 test.db-litestream
-rw-r--r-- 1 ralf ralf       51 Jun 15 08:57 test.primary.yml

```
(NOTE that on exit of command line sqlite3, the WAL is cleared, suggesting that SQLITE_FCNTL_PERSIST_WAL wasn't called correctly in litestream)

(other vmtest9 window running litestream primary is now spamming this nonstop and consuming a lot of CPU)
`/home/ralf/test.db: sync error, retrying: cannot verify wal state: stat /home/ralf/test.db-wal: no such file or directory
`
just prior to this spam, it output:
```
/home/ralf/test.db: init: cannot determine last wal position, clearing generation; primary wal header: EOF
/home/ralf/test.db: sync: new generation "9303baf519acafe4", no generation exists

```

(on ralf@lxc)
```
/home/ralf/test.db: wal segment applied: 72a73404ef700afb/0000000000000000:0000000000000000
/home/ralf/test.db: wal segment applied: 72a73404ef700afb/0000000000000000:0000000000000020
/home/ralf/test.db: wal segment applied: 72a73404ef700afb/0000000000000000:0000000000000438

```
(on ralf@lxc, after ^C on vmtest9 server)
`/home/ralf/test.db: stream error, retrying: stream connect: Get "http://192.168.99.9:9090/stream?generation=72a73404ef700afb&index=0000000000000000&path=%2Fhome%2Fralf%2Ftest.db": dial tcp 192.168.99.9:9090: connect: connection refused
`

```
ralf@vmtest9:~$ litestream replicate -config test.primary.yml
litestream 80f8de4d9ed16b7ae6f607bde85d90916784de7d
initialized db: /home/ralf/test.db
http server running at http://localhost:9090
litestream initialization complete
/home/ralf/test.db: init: cannot determine last wal position, clearing generation; primary wal header: EOF
/home/ralf/test.db: sync: new generation "7233d0fcd2dc635d", no generation exists
http: stream generation mismatch, using primary position: client.pos=72a73404ef700afb/0000000000000000:0000000000000000
http: stream connected: pos=7233d0fcd2dc635d/0000000000000000:0000000000000000 snapshot=true

ralf@vmtest9:~$ ls -ld test*
-rw-r--r-- 1 ralf ralf 61387776 Jun 15 09:02 test.db
drwxr-xr-x 3 ralf ralf     4096 Jun 15 09:03 test.db-litestream
-rw-r--r-- 1 ralf ralf    32768 Jun 15 09:03 test.db-shm
-rw-r--r-- 1 ralf ralf     1080 Jun 15 09:03 test.db-wal
-rw-r--r-- 1 ralf ralf       51 Jun 15 08:57 test.primary.yml

```
(on remote)
`/home/ralf/test.db: snapshot applied
`
(on vmtest9)
```
ralf@vmtest9:~$ sqlite3 test.db 'update card_result set batch=batch+1'
ralf@vmtest9:~$ ls -ld test*
-rw-r--r-- 1 ralf ralf 61387776 Jun 15 09:04 test.db
drwxr-xr-x 3 ralf ralf     4096 Jun 15 09:03 test.db-litestream
-rw-r--r-- 1 ralf ralf       51 Jun 15 08:57 test.primary.yml

```
I'm not sure of the circumstances, but sometimes it gets into a happy state when the WAL file is preserved whenever you exit. So this leads me to believe that the code that does SQLITE_FCNTL_PERSIST_WAL isn't always triggered for some reason.

**Comment by benbjohnson** [comment]
@ralferoo Thanks for digging into that. I was using a connection that didn't have `SQLITE_FCNTL_PERSIST_WAL` on it for the replication so that definitely sounds like the issue. I've removed that connection in the latest refactor so I'll close this issue.
