### ISSUE TITLE
Complete database reupload after restore

### ISSUE THREAD

**Issue by borisghidaglia** [benbjohnson/litestream#393]
Hello,

First of all, thanks for creating litestream !

I was doing some testing before using it in production, and a behaviour I did not expected happened.

The complete database is reuploaded when following these steps :
 
* run replicate db to s3 command (then stop the command when the snapshot is written)
* remove all local litestream and db related files (`.{dbname}.db-litestream` folder, `{dbname}.db`, `{dbname}.db-shm`, `{dbname}.db-wal`)
* restore the db locally
* run replicate db to s3 command again --> db reuploads here

After these steps, I end up with 2 generations uploaded on s3, with the same size.

Is there something I'm doing wrong / something I misunderstood ?

Thanks

PS: sorry for the edit, I issued my draft by mistake

**Comment by benbjohnson** [comment]
@borisghidaglia Sorry for the really late reply. The `restore` command simply restores the database file and not any Litestream metadata so it isn't able to restart the same generation. Having multiple generations is fine as the older one will eventually get removed based on the retention period in Litestream.
