### ISSUE TITLE
Difficulties with litestream with minio over tailscale

### ISSUE THREAD

**Issue by koivunej** [benbjohnson/litestream#398]
Hi there,

Tried the $subject combination today as an "extended Getting Started". Trouble was with trying to get `s3://bucket.some_name_or_ip_address:9000/filename` go to my other end of tailscale connection. Using a name defined in `/etc/hosts` seemed to output an AWS error, I presume for minioadmin/minioadmin not working there as expected. What worked was mapping `localhost` via `/etc/hosts` to the remote ip address.

Could there had been a different way to set up the ip or hostname of the service masquerading as s3? Of course mine wasn't a real production issue. If there would had been an obvious way to bypass I couldn't figure out with the please do share it!

Version: v0.3.8 through Debian package

**Comment by benbjohnson** [comment]
@koivunej Sorry for the late reply. You can set up a replica using a config file and it'll give you more options than the URL-based approach. There are some examples in the config docs: https://litestream.io/reference/config/#s3-replica

**Comment by koivunej** [comment]
Aah yes, I failed to the see find the `endpoint` which I think is the way to go after looking at it for a longer time. Thanks!

**Comment by marcosvm** [comment]
@koivunej can you share the non-sensitive parts of your `livestream.yml` config? I'm not figuring this out correctly.

**Comment by koivunej** [comment]
When originally trying litestream out, I wasn't using a litestream.yml because I failed to understand the docs in haste :)

I cannot reproduce this right now because away from keyboard but the original description has everything I was using. I think the solution was really to:
- use `s3://buckee.localhost:9000/filename`
- temporarily map `localhost` to a non-localhost ip address (which happened to be a tailnet ip)

But for this case, we used an application which continiously wrote to the sqlite file, quite lot actually and were not really able to use the syched file or get litestream to catch up even by stopping the writing process and waiting. The amount that needed to be synched was most likely more than what was the bandwidth available to transfer the WAL files.

Apologies for not having documented the setup better, let me know if you have any further questions.

**Comment by marcosvm** [comment]
Thanks for the feedback. The configuration below worked for me, but I had to create a service account on minio to generate credentials:

```
dbs:
  - path: mydb.db
    replicas:
      - type: s3
        bucket: mybkt
        endpoint: http://<TAILSCALE_IP>:9000
        skip-verify: true
        access-key-id: <ACCESS-KEY-ID>
        secret-access-key: <SECRET-ACCESS-KEY>
```
