### ISSUE TITLE
Missing link to source on litestream.io

### ISSUE THREAD

**Issue by bouk** [benbjohnson/litestream#40]
Hi Ben, long time no talk. I was having some trouble finding this repository, there doesn't seem to be a link on litestream.io, also not on the 'build from source' page: https://litestream.io/install/source/

Would be useful to add a link! I also hope you'll write a blogpost about how litestream works.

Thanks for the cool project!

**Comment by benbjohnson** [comment]
hey @bouk! It has been a long time!

There's a teeny-tiny GitHub icon in the upper right hand corner but that's probably not very intuitive. :)

I added a link on the _Install from Source_ page and I added "GitHub" as header on the site.

**Comment by benbjohnson** [comment]
I have a link for some basics about the internals but I'll be writing some blog posts in the future too: https://litestream.io/how-it-works/

**Comment by bouk** [comment]
Oh interesting, my ad blocker was hiding the github icon. I have it block social media widgets which it might've identified it as. Thanks for adding a big link 👍
