### ISSUE TITLE
Litestream exhausts memory, but only on fly.io

### ISSUE THREAD

**Issue by mtlynch** [benbjohnson/litestream#403]
I've been running into a strange issue with Litestream for the past few months. I finally sat down and debugged it for a few hours today, but I'm stuck and hoping for pointers on what to try next.

## Background

I see this issue with my app [PicoShare](https://github.com/mtlynch/picoshare). It's a web app that lets users upload files and then share links to those files. It stores all file data and metadata in SQLite (file data is broken into BLOBs of 327680 byte each). 

PicoShare uses Litestream to replicate the data to cloud storage.

## Issue

I've seen that my PicoShare instances on fly.io will die due to OOM. Usually this happens immediately after I upload a file, but sometimes it happens when I'm not touching the DB at all.

Sometimes fly.io reports that the litestream process exhausted memory, sometimes fly.io reports that the picoshare process exhausted memory, and sometimes it reports both:

```text
2022-07-24T15:27:57.576 app[c3cc923c] iad [info] [ 145.959415] Out of memory: Killed process 546 (picoshare) total-vm:1142388kB, anon-rss:108268kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:340kB oom_score_adj:0

2022-07-24T15:27:57.599 app[c3cc923c] iad [info] subprocess exited, litestream shutting down

2022-07-24T15:27:57.833 app[c3cc923c] iad [info] [ 146.215993] Out of memory: Killed process 523 (litestream) total-vm:1582400kB, anon-rss:201436kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:596kB oom_score_adj:0 
```

## Repro

If I deploy a PicoShare instance to fly.io with shared CPU and 256 MB of RAM, it consistently OOM exits

```bash
# Clone PicoShare
git clone https://github.com/mtlynch/picoshare.git

LITESTREAM_ACCESS_KEY_ID=YOUR-ACCESS-ID # Replace with your bucket access key ID
LITESTREAM_SECRET_ACCESS_KEY=YOUR-SECRET-ACCESS-KEY # Replace with your bucket access key

# Create a PicoShare instance on fly.io
REGION="iad"
RANDOM_SUFFIX="$(head /dev/urandom | tr -dc 'a-z0-9' | head -c 6 ; echo '')"
APP_NAME="picoshare-${RANDOM_SUFFIX}"

curl -s -L https://raw.githubusercontent.com/mtlynch/picoshare/master/docs/deployment/fly-assets/make-fly-config | \
  bash /dev/stdin "${APP_NAME}"
fly apps create --name "${APP_NAME}"

fly secrets set \
  "LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}" \
  "LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}"
```

You then need to  Edit your fly.toml to add these vars under [env]
```toml
LITESTREAM_BUCKET="YOUR-CLOUD-STORAGE-BUCKET"
LITESTREAM_ENDPOINT="YOUR-CLOUD-STORAGE-ENDPOINT"
```

Finally, deploy to fly.io:

```bash
fly deploy \
  --region="${REGION}" && \
  PICOSHARE_URL="https://${APP_NAME}.fly.dev/" && \
  echo "Your PicoShare instance is now ready at: ${PICOSHARE_URL}"
```

Visit `$PICOSHARE_URL` and try uploading a file that's at least 250 MB (e.g., [*Big Buck Bunny*](https://mirror.clarkson.edu/blender/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4)).

**Result**: The upload fails because fly.io kills the process due to OOM.

## Can't repro on Docker

The strange thing is that if you run the same command in a memory-constrained Docker container, it doesn't fail. You can even run in a Docker container with 64 MB of RAM, and everything works fine.

```bash
RAM_LIMIT="64m"
PORT=3001
PS_SHARED_SECRET="somesecretpass"
LITESTREAM_BUCKET=YOUR-LITESTREAM-BUCKET
LITESTREAM_ENDPOINT=YOUR-LITESTREAM-ENDPOINT
LITESTREAM_ACCESS_KEY_ID=YOUR-ACCESS-ID
LITESTREAM_SECRET_ACCESS_KEY=YOUR-SECRET-ACCESS-KEY

docker run \
   --memory "${RAM_LIMIT}" \
  --env "PORT=${PORT}" \
  --env "PS_SHARED_SECRET=${PS_SHARED_SECRET}" \
  --env "LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}" \
  --env "LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}" \
  --env "LITESTREAM_BUCKET=${LITESTREAM_BUCKET}" \
  --env "LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT}" \
  --publish 3001:3001/tcp \
  --name picoshare \
  mtlynch/picoshare:1.1.7
```

I can upload a 260 MB file, and PicoShare happily accepts the upload, replicates it with Litestream, and serves it all on just the 64 MB:

```bash
$ docker stats
CONTAINER ID   NAME        CPU %     MEM USAGE / LIMIT   MEM %     NET I/O         BLOCK I/O        PIDS
1ababd398113   picoshare   3.82%     63.68MiB / 64MiB    99.50%    278MB / 208MB   6.09GB / 7.1MB   21
```

It's noticeably slower but it doesn't crash.

## Can't repro without Litestream

If I disable Litestream (e.g. comment out `LITESTREAM_BUCKET` in my `fly.toml` file, uploading the 260 MB file doesn't exhaust memory and works fine as well.

## Other attempts

I tried [running with `litestream replicate` with the `-trace` flag](https://github.com/mtlynch/pico-fly-repro/blob/9687f9ff6824b84ac7eee230ca0032b7ba57cf05/docker-entrypoint#L45L52) and a [fly.io persistent volume](https://github.com/mtlynch/pico-fly-repro/blob/9687f9ff6824b84ac7eee230ca0032b7ba57cf05/fly.toml#L17L19), but it doesn't seem to write anything to the file:

```bash
$ ls -l /litestream-trace/litestream-tracing.log
-rw-r--r-- 1 root root 0 Jul 24 15:56 /litestream-trace/litestream-tracing.log 
```

### Ideas?

Any ideas of anything else I can try to debug this further or avoid the OOM crashes?

**Comment by mtlynch** [comment]
Actually, scratch that. I can repro this on fly.io without Litestream, so I think this is just a memory leak somewhere in my app.

**Comment by benbjohnson** [comment]
@mtlynch Do you have two memory profiles over a period of time for your app? That can help isolate the issue. Let me know if you want to hop on a zoom to try to debug it.

**Comment by mtlynch** [comment]
@benbjohnson Thanks for the offer! I've never tried using memory profiling for Go, but @eatonphil's [recent blog post](https://notes.eatonphil.com/implementing-a-jq-clone-in-go.html) made it look easy, so I'm going to try and find some time to experiment with it this week.
