### ISSUE TITLE
Replication not working after removal of streaming support

### ISSUE THREAD

**Issue by hifi** [benbjohnson/litestream#415]
868d564 removed streaming replication and seemingly also the mechanism how WAL files are notified to be uploaded.

More specifically the call to this function was removed and no one's calling it anymore which seems to be the root cause: https://github.com/benbjohnson/litestream/blob/868d5649885ac35111c93346f40fc0f0dd061128/file_replica_client.go#L520

**Comment by hifi** [comment]
Fixed by reverting main :upside_down_face:

**Comment by cfstras** [comment]
Do you mean reverting in your local fork? That wouldn’t fix the issue for other people…

**Comment by hifi** [comment]
No I meant that the main branch of this repo was reverted to v0.3.9 that didn't have this issue and it will not regain the exact same bug anymore as streaming will not be added back.

**Comment by cfstras** [comment]
Ah, just realized the mentioned commit isn’t in `main`. Thanks for the clarification!
