### ISSUE TITLE
Is it possible to use replica as read-only database?

### ISSUE THREAD

**Issue by diskman** [benbjohnson/litestream#426]
Sorry, it might be stupid question but I would really like somehow use replica as read only data source (without need of additional restore). Is it somehow possible to connect using sql lite drivers to replica and use it as read only sql lite db? Currently I have set up which use the replication to s3 bucket and I was thinking to set up SFTP replication to another host where the data could be consumed by some application.

**Comment by benbjohnson** [comment]
Hi @diskman, sorry, that's not currently possible with Litestream. The closest thing would be something like [LiteFS](https://github.com/superfly/litefs) which does live replication and it will have S3 streaming backup support coming soon.
