### ISSUE TITLE
AWS S3 region detection prior to authentication causes access denied

### ISSUE THREAD

**Issue by CJRChang** [benbjohnson/litestream#427]
In environments where AWS S3 credentials are only valid after `session.NewSession` (e.g. when using [assume role with web identity](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-oidc) which uses `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` as the authentication mechanism, supported by `aws-sdk-go`) litestream can encounter access denied errors [when attempting to fetch the bucket region](https://github.com/benbjohnson/litestream/blob/868d5649885ac35111c93346f40fc0f0dd061128/s3/replica_client.go#L85) since the credentials aren't valid yet.

**Comment by CJRChang** [comment]
One use case where this could be encountered is when attempting to use litestream on (EKS with a service account)[https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html].

In this particular scenario, the container won't have assumed the correct role and will fall back to the underlying node IAM role instead.

**Comment by irl-segfault** [comment]
I tried to work around this by setting the `region` variable in the litestream config, i.e

```
dbs:
  - path: /var/lib/myapp/db
    replicas:
      - url: s3://golinks-bucket/db
        region: us-west-2
```

still not having luck getting Litestream to work with IAM Role Service Accounts (IRSA) in K8s.  I believe the SDK version in use should be sufficient, so maybe I'm doing something dumb.

**Comment by ekristen** [comment]
I opened a PR to fix this https://github.com/benbjohnson/litestream/pull/455 -- basically the `defaults` package isn't really supposed to be used the way it was, switched it to `aws.Config` so the default credential chain handler is called. You can test this via my docker image `ghcr.io/ekristen/litestream:0.3.9-aws-fix`
