### ISSUE TITLE
Prefix messages in syslog

### ISSUE THREAD

**Issue by solracsf** [benbjohnson/litestream#428]
Take this log line as example:
```
sqlite.db(s3): wal segmented deleted before 970f6b9b67f67fe9/00003ec6: n=403
```
something like
```
[INFO] sqlite.db(s3): wal segmented deleted before 970f6b9b67f67fe9/00003ec6: n=403
```
would be more appropriate. Same for `[WARN]`, `[ERROR]` or `[FATAL]` if applicable.

**Comment by hifi** [comment]
As of current v0.3.x this is fixed by updating to slog.
