### ISSUE TITLE
Validation of compatiability with Storj.io - Web3 object storage platform

### ISSUE THREAD

**Issue by kmozurkewich** [benbjohnson/litestream#429]
Storj.io is S3-compatible - would it be possible to validate that litestream is compatible?  Storj has specific region hostname/endpoint values for the S3 connection, though it works with minio and a custom endpoint.

**Comment by benbjohnson** [comment]
Yeah, you should be able to just set the different fields in the S3 replica client config and test it out. There's not a validating test harness right now so it's more a matter of just giving it a try. https://litestream.io/reference/config/#s3-replica
