### ISSUE TITLE
ARM64 Build

### ISSUE THREAD

**Issue by cablespaghetti** [benbjohnson/litestream#43]
Hi,

Great project! I’m dreaming up use cases for it already...

It would be great if this project had ARM64 Linux builds available. This could potentially be quite easy with gox: https://github.com/mitchellh/gox

Thanks!

**Comment by benbjohnson** [comment]
ARM64 builds is definitely something I want to add. I've actually been waiting for someone to mention it before I put in the effort to make release builds. What's your use case? Are you using ARM64?

**Comment by cablespaghetti** [comment]
I think the most common use case you'll get with this is people wanting to use it on their Raspberry Pis, which making arm64 binaries would be great for.

My current use case is my multi-arch (two amd64 and 1 arm64 nodes) k3s cluster at home for experimenting. So actually it's multi-arch/manifest list Docker images I'm most keen on. However with AWS Graviton 2 instances being so cost effective I am professionally interested in everything supporting ARM.

**Comment by angelbarrera92** [comment]
Don't forget about RPI owners :)
it is not arm64, but armv7 :)

**Comment by benbjohnson** [comment]
I have support for 32-bit & 64-bit ARM release builds. You can find them on this alpha release which is mostly the same as v0.3.3 except for some minor changes. The `arm64` build seems to work on AWS Gravitron instances but I don't have a 32-bit ARM machine to test with. The `arm` builds should work with Rasperry Pi. I need to order one to do some testing. 

https://github.com/benbjohnson/litestream/releases/tag/v0.3.4-alpha11
