### ISSUE TITLE
Validation via CLI

### ISSUE THREAD

**Issue by asymmetric** [benbjohnson/litestream#431]
AFAICT, it's only possible to perform validation by adding the `validation-interval` key to the configuration file.

It would be great if this could be performed from the CLI as well. This would allow me to have more confidence that litestream is working as intended.

**Comment by benbjohnson** [comment]
There's a timing bug with validation that produces false negatives so it's being removed in v0.4.0. The best way to verify it's working is to pause writes to the database, call `PRAGMA wal_checkpoint(TRUNCATE)`, call `litesteam restore`, and then compare the `md5` checksum of each database.
