### ISSUE TITLE
Can litestream be used with a key protected by a passphrase?

### ISSUE THREAD

**Issue by georgpfolz** [benbjohnson/litestream#451]
Currently I get the error: `monitor error: cannot parse sftp key path: ssh: this private key is passphrase protected`.

The keys work well when I ssh from terminal and even some other software (without asking for the passphrase) because I already set up an ssh-agent. But with litestream I get this error message.

I there isn't a solution already of which I'm not aware of, it would be nice if the passphrase could be written into the config file.

(I'm currently working on Catalina 10.15.7 on a MacBook)

**Comment by hifi** [comment]
If writing the passphrase to the config file is acceptable in your use case why can't you generate a Litestream specific SSH key without passphrase protection as writing it in a file makes it essentially the same?

**Comment by georgpfolz** [comment]
> If writing the passphrase to the config file is acceptable in your use case why can't you generate a Litestream specific SSH key without passphrase protection as writing it in a file makes it essentially the same?

I get your point but I still believe a key without a passphrase is somewhat less secure, as it renders the server unaccessible even if it is stolen somehow. Of course someone having access to my computer might be able the find the passphrase if it's written into the config file.

But I guess that's what I'll be ending doing.

**Comment by benbjohnson** [comment]
I agree with @hifi. I think the best option is to make a key without a passphrase for Litestream. Since the key would live next to the passphrase in the config file, it doesn't seem much less secure.

**Comment by dentarg** [comment]
Seeing how the litestream [can expand environment variables](https://litestream.io/reference/config/#variable-expansion), being able to use SSH keys with passphrases makes a lot of sense, don't it?
