### ISSUE TITLE
Clarification on "Multiple applications replicating into location can corrupt"

### ISSUE THREAD

**Issue by cideM** [benbjohnson/litestream#454]
This isn't mentioned anywhere in the Setup guides, as far as I can tell, but it is mentioned in the [Tips & Caveats](https://litestream.io/tips/#multiple-applications-replicating-into-location-can-corrupt). Do I really need one bucket per replica? Or can I also have multiple apps replicating into the same _bucket_ but with a different _replica name_?

```shell
$ aws s3 ls my-replica/
PRE dev-a/
PRE dev-b/
PRE prod/
```

would this be bad?

**Comment by hifi** [comment]
You can replicate to a single bucket but different paths. The wording is slightly wrong as it means the _exact_ same location and not a whole bucket.
