### ISSUE TITLE
Google Cloud Storage Support?

### ISSUE THREAD

**Issue by willnewby** [benbjohnson/litestream#46]
Hello! This is a super-awesome project, you're inspiring me to build more of my sideprojects on SQLite. Thank you for making it!

Are there any plans for Google Cloud/GCS support in the future?

Thanks again for the great project!

**Comment by benbjohnson** [comment]
Thanks, Will! GCS is S3-compatible so it should work (or at least with some minor tweaks). I have an issue open for documenting S3-compatible tools like GCS, Minio, etc so I'll close this one. https://github.com/benbjohnson/litestream/issues/41

**Comment by willnewby** [comment]
That's excellent, I had no idea GCS was S3-compatible. Thanks!
