### ISSUE TITLE
[Docker] Error using the official image

### ISSUE THREAD

**Issue by Guikingone** [benbjohnson/litestream#463]
Hi 👋🏻 

I might be the only one to face this issue but when using the Docker image, the following error occurs: 

```bash
docker run -v ... -v litestream.yml:/etc/litestream.yml litestream/litestream replicate # the data volume is omitted just for this code block

read /etc/litestream.yml: is a directory
```

It seems that even when the file is shared, Litestream does not consider it as a file 🤔 

Thanks again for the feedback and have a great day 🙂

**Comment by hifi** [comment]
I think your problem is that you need to have path to the source file, otherwise Docker creates a volume. If it's a local file try `-v ./litestream.yml:/etc/litestream.yml`.
