### ISSUE TITLE
When will a new release be created?

### ISSUE THREAD

**Issue by manglav** [benbjohnson/litestream#464]
The current release version is from ~9 months ago, and I see at least a few commits since then. Is it possible to generate a new release?

**Comment by benbjohnson** [comment]
@manglav Yes, there's a lot of changes that were going to be for live replication but I need to back those out. I'll probably revert `main` back to `v0.3.9` and just reapply non-replication commits back on and tag it as `v0.3.10`. I'll try make some time this weekend to do that.

**Comment by cristaloleg** [comment]
Any blockers so far? 🙂

**Comment by benbjohnson** [comment]
@cristaloleg Mostly just time. @hifi has a good suggestion to just include a smaller subset of the commits that I was going to rebase back onto `main` and cut smaller releases. I'll give that a go. If I have enough time tomorrow, I'll get a couple merged in, do some release testing, and cut a new release.

**Comment by SeriousM** [comment]
Will there a windows release as well? There is a stable release of v0.3.9 (July 2022) which contains only mac/linux bins. The last release with windows bins included was v0.3.7 (December 20**21**).

**Comment by hifi** [comment]
Windows support was dropped due to not being maintained.

**Comment by hifi** [comment]
There's been a couple of releases lately. Windows support exists in the code and is now tested by the CI but no release binaries are being built for now.

**Comment by jlcastillo** [comment]
I think it doesn't work in Windows yet, can we reopen it?

```
c:\utils\litestream-0.3.13>go install ./cmd/litestream
# github.com/benbjohnson/litestream
.\litestream.go:58:19: conn.SetFileControlInt undefined (type *sqlite3.SQLiteConn has no field or method SetFileControlInt)
.\litestream.go:58:53: undefined: sqlite3.SQLITE_FCNTL_PERSIST_WAL
```

```
c:\utils\litestream-0.3.13>sqlite3 --version
3.43.2 2023-10-10 12:14:04 4310099cce5a487035fa535dd3002c59ac7f1d1bec68d7cf317fd3e769484790 (32-bit)
```
