### ISSUE TITLE
Sqleet Support?

### ISSUE THREAD

**Issue by PrimeDominus** [benbjohnson/litestream#47]
Does this work with https://github.com/resilar/sqleet and, if so, any recommendations on how to make it work best? I've found sqleet to be the best for encrypted sqlite.

**Comment by benbjohnson** [comment]
I'm not sure if it works with `sqleet`. Litestream treats the WAL page data as opaque but it does need to read the WAL frame headers so if those are encrypted then it probably won't work. I've thought about adding encryption to Litestream when sending WAL files to S3 but I haven't tried anything yet.

**Comment by benbjohnson** [comment]
I'm closing this as Litestream won't work with encrypted databases in general as there is metadata  it needs to work.

**Comment by tejpochiraju** [comment]
@benbjohnson - I guess your comment answers this question already. However, for completeness, does this mean that Litestream won't work with the [SQLite Encryption Extension](https://www.sqlite.org/see/doc/release/www/readme.wiki)?

**Comment by benbjohnson** [comment]
@tejpochiraju Yes, that's correct. SEE is a licensed extension and not open source so it makes it difficult to distribute it inside Litestream.

**Comment by tejpochiraju** [comment]
Thanks, Ben. Maybe we are getting our terms mixed up here but my question was more specifically whether Litestream would/could replicate a DB if we had a licensed SEE extension. A theoretical question, we don't use SEE (yet anyway).

**Comment by benbjohnson** [comment]
Ah, sorry I wasn't clear. The encrypted versions of SQLite typically use a drop-in replacement for SQLite code and any tools accessing the database need to use the same drop-in replacement code. At least that's my understanding.

Litestream could possibly work if it used Sqleet or SEE compiled into it but that gets tricky with SEE as it's not open source.

**Comment by tejpochiraju** [comment]
Got it, thanks! If this gets enough demand and you see it as a suitable inclusion, I would be happy to contribute/pay in a model you deem suitable.
