### ISSUE TITLE
Replicate once then quit?

### ISSUE THREAD

**Issue by onionhammer** [benbjohnson/litestream#487]
I would like to be able to simply replicate the database out to a backup once? I would like to be able to run a command locally to overwrite a backup in azure blob storage, then start a container with what was a local database (which replicates from the same storage account)

**Comment by hifi** [comment]
That's essentially what I described in #486 with an implementation plan. I'm going to implement something like this.

**Comment by onionhammer** [comment]
Closing in favor of #486
