### ISSUE TITLE
Small typo in tutorial

### ISSUE THREAD

**Issue by amercader** [benbjohnson/litestream#50]
In the [Continuous replication](https://litestream.io/getting-started/#continuous-replication) section you insert a blue grape:

    INSERT INTO fruits (name, color) VALUES ('grape', 'blue');

But you get back a purple one when restoring `fruits3.db`:
```
SELECT * FROM fruits;
apple|red
banana|yellow
grape|purple
```

Nothing major of course, but it confused me for a second.

Thanks for this project, it looks really useful and simple to use.

**Comment by benbjohnson** [comment]
lol, good catch! That bug cracked me up. It's fixed and I pushed up the change. It should be live in a few minutes. Thanks!
