### ISSUE TITLE
[Docker] arm/v7 not available on Dockerhub for latest version

### ISSUE THREAD

**Issue by pierot** [benbjohnson/litestream#501]
It seems the latest build does not contain the arm/v7 version. Any chance this could be fixed and included? Thanks

**Comment by benbjohnson** [comment]
I pulled it out while debugging some CI issues and forgot to put it back in. I fixed it in https://github.com/benbjohnson/litestream/pull/502.

Can you give that a try? The image name is [litestream/litestream:pr-502](https://hub.docker.com/layers/litestream/litestream/pr-502/images/sha256-902c2a587251c3e84b67ba7e31f8f44ce6f14e07c8a91213bbf36c00f37c8a89?context=explore).

**Comment by pierot** [comment]
@benbjohnson That works. Thanks!

**Comment by Alexander160786** [comment]
Что вы хотите от меня

вт, 15 авг. 2023 г., 08:55 Pieter Michels ***@***.***>:
