### ISSUE TITLE
Rosetta 2 required for M1/M2 Macs

### ISSUE THREAD

**Issue by clintonb** [benbjohnson/litestream#505]
I tried installing on a brand new Mac Mini, and encountered an error message: `Bad CPU type in executable`. 

I was able to work around this by installing Rosetta 2 with the command below:

`softwareupdate --install-rosetta`

Please update the docs to note this requirement.

I can add this, but am in a hurry, so creating the ticket to avoid forgetting.

**Comment by benbjohnson** [comment]
Hi @clintonb. 👋  Did you download via homebrew or by downloading from the releases page? I just started building macOS ARM64 builds so they're on the releases page but I need to figure out the Homebrew syntax to get that working for both amd64 & arm64.

**Comment by clintonb** [comment]
Homebrew.

**Comment by benbjohnson** [comment]
This has been fixed in the latest release ([v0.3.12](https://github.com/benbjohnson/litestream/releases/tag/v0.3.12)). It'll download the arm64 version for M1/M2 and download the amd64 version for Intel CPUs.
