### ISSUE TITLE
Exception when upgrading to litestream 0.3.12

### ISSUE THREAD

**Issue by onionhammer** [benbjohnson/litestream#511]
goroutine 1 [running]:
github.com/benbjohnson/litestream.(*Replica).Logger(0x40001a40f0)
        /src/litestream/replica.go:102 +0x90
github.com/benbjohnson/litestream.(*Replica).Restore(0x40001a40f0, {0x16ab268, 0x1fec440}, {{0xffffea509ea8, 0x11}, {0x0, 0x0}, {0x40008ba284, 0x10}, 0x7fffffff, ...})
        /src/litestream/replica.go:1097 +0x648
main.(*RestoreCommand).Run(0x1fec440, {0x16ab268, 0x1fec440}, {0x400013a140, 0x4, 0x4})
        /src/litestream/cmd/litestream/restore.go:83 +0x6a8
main.(*Main).Run(0x40000021a0?, {0x16ab268, 0x1fec440}, {0x400013a130, 0x5, 0x5})
        /src/litestream/cmd/litestream/main.go:121 +0x120
main.main()
        /src/litestream/cmd/litestream/main.go:41 +0x6c

Command:

```

    # Run the litestream restore from docker, volume mounting to ./database
    docker run --rm -it `
        -v ${PWD}/database:/database `
        -e LITESTREAM_AZURE_ACCOUNT_KEY=$($keys[0].value) `
        litestream/litestream restore -if-replica-exists `
        -o /database/data.db "abs://$accountName@$database/data.db"

```

**Comment by benbjohnson** [comment]
Thanks for reporting the issue. This should fix it: https://github.com/benbjohnson/litestream/pull/512

If possible, can you give it a try to confirm?

**Comment by onionhammer** [comment]
@benbjohnson Yep, that seems to fix it

```
    # Run the litestream restore from docker, volume mounting to ./database
    docker run --rm -it `
        -v ${PWD}/database:/database `
        -e LITESTREAM_AZURE_ACCOUNT_KEY=$($keys[0].value) `
        litestream/litestream:pr-512 restore -if-replica-exists `
        -o /database/data.db "abs://$accountName@$database/data.db"
```

**Comment by hifi** [comment]
Shouldn't `db` be always set? Now the logs are missing which database is being restored. Fixing the crash is good, but shouldn't it also be assured it's always set?

**Comment by benbjohnson** [comment]
@hifi If you're restoring directly from a replica URL then there's no associated database. The `db` is only set when it's looked up in the config file.

**Comment by hifi** [comment]
Ah, right, that's why my testing didn't hit that!

**Comment by benbjohnson** [comment]
I cut a new release with this fix: https://github.com/benbjohnson/litestream/releases/tag/v0.3.13
