### ISSUE TITLE
Verbose parameter removed in version 0.3.13

### ISSUE THREAD

**Issue by ArjonBu** [benbjohnson/litestream#533]
I am running litestream as an initContainer to restore the database if the file doesn't exist (as described [here](https://litestream.io/guides/kubernetes/#automatic-recovery)) but it seems that in the latest version the parameter "-v" doesn't work. 

It works on the image version 0.3.9 but not on latest one "0.3.13". 

2023/12/10 17:48:59 ERROR failed to run error="flag provided but not defined: -v"

**Comment by hifi** [comment]
It was removed due to being redundant after logging changes.

**Comment by ArjonBu** [comment]
Ah I see. I think it's still mentioned on your docs. I am closing this issue. 

Thank you!

**Comment by MathiasPius** [comment]
This change actually broke one of my deployments, despite it being a minor change: https://github.com/MathiasPius/kronform/pull/12/files#diff-5bee35a953721037aeff3349e4561fa0d19fd4df7e86071dd71b4dd7ef710ca5R72

The change seems innocuous, but I think it would have made sense to issue a major version bump or at least mention it explicitly in the changelog.

**Comment by gustavovalverde** [comment]
@hifi just to mention the command was removed, but it's still showing as an argument in the CLI documentation:

```shell
flag provided but not defined: -v

The restore command recovers a database from a previous snapshot and WAL.

Usage:

        litestream restore [arguments] DB_PATH

        litestream restore [arguments] REPLICA_URL

Arguments:

        -config PATH
            Specifies the configuration file.
            Defaults to /etc/litestream.yml

        -no-expand-env
            Disables environment variable expansion in configuration file.

        -replica NAME
            Restore from a specific replica.
            Defaults to replica with latest data.

        -generation NAME
            Restore from a specific generation.
            Defaults to generation with latest data.

        -index NUM
            Restore up to a specific hex-encoded WAL index (inclusive).
            Defaults to use the highest available index.

        -timestamp TIMESTAMP
            Restore to a specific point-in-time.
            Defaults to use the latest available backup.

        -o PATH
            Output path of the restored database.
            Defaults to original DB path.

        -if-db-not-exists
            Returns exit code of 0 if the database already exists.

        -if-replica-exists
            Returns exit code of 0 if no backups found.

        -parallelism NUM
            Determines the number of WAL files downloaded in parallel.
            Defaults to 8

        -v
            Verbose output.

```
