### ISSUE TITLE
Website menu truncated on mobile

### ISSUE THREAD

**Issue by kalafut** [benbjohnson/litestream#551]
Hi, and thank you for Litestream!

Some minor website feedback. The hamburger menu on smaller screens, which expands horizontally, is truncated and can't be scrolled. I didn't even notice on my one device that was cutting off the whole last element ("Slack"), but on a slightly larger device, I could see the "S" peeking through:

![Screen Shot 2023-12-25 at 07 11 58](https://github.com/benbjohnson/litestream/assets/211880/9ce93c4f-5000-445b-9c96-38b06bb765fd)

**Comment by hifi** [comment]
Indeed, thanks for reporting!

Probably some of the recent updates broke it or it's always been broken, I'll check it out.

**Comment by hifi** [comment]
Now the navigation works as intended and opens vertically on mobile.

![image](https://github.com/benbjohnson/litestream/assets/106598/3b560fee-659c-401b-8644-4af65f384060)
