### ISSUE TITLE
32-bit ARM Support

### ISSUE THREAD

**Issue by bwghughes** [benbjohnson/litestream#57]
Ran compilation as per instructions:

```
/db.go:1374:46: constant 9223372036854775807 overflows int
./db.go:1376:22: constant 9223372036854775807 overflows int
./db.go:1699:3: constant 9223372036854775807 overflows int
./replica.go:999:14: constant 9223372036854775807 overflows int
```

Which I think is due to [this](https://github.com/golang/go/issues/23086) . I attempted a patch, but am not a Go hacker, and got stuck !!

``` > uname -a
Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
```

``` > go version
go version go1.15.8 linux/arm
```

**Comment by benbjohnson** [comment]
Thanks, @bwghughes. I haven't done any testing on 32-bit processors yet. There's an ARM64 issue (https://github.com/benbjohnson/litestream/issues/43) but I'll try to get it working on arm7l as well.

**Comment by bwghughes** [comment]
Thanks Ben - much appreciated. I love the concept of Litestream - I'm a huge SQLIte fan, this is a great, great idea.

**Comment by bwghughes** [comment]
Ben - also, running this on an M1 Mac. Will report back in compat issues.

**Comment by angelbarrera92** [comment]
I'm interested too!

**Comment by benbjohnson** [comment]
I have release builds for 32-bit & 64-bit ARM merged in. You can try them out on this alpha release: 

https://github.com/benbjohnson/litestream/releases/tag/v0.3.4-alpha11

I can probably get `darwin/amd64` builds too but I'm not sure how notarizing works if I'm running from a non-M1 machine. Hopefully it's fine. :)
