### ISSUE TITLE
Rules for how to develop an application with a litestream-able SQLite database

### ISSUE THREAD

**Issue by berezovskyi** [benbjohnson/litestream#58]
Hello,

First of all, thank you for this great project! I have never used SQLite in a position where I would have a live replication set up, so I wanted to have a hands-on test scenario to see how the tool works. Unfortunately, I cannot get it to work in a meaningful way with what I have tried so far:

- Brave history
- Firefox history

I see lots of different errors. I understand fully that what I am trying to do is... questionable. But I would like to understand how the tool works under some kind of load and I don't have any so far. What are the rules that I need to follow in my application to make sure litestream replication does not fail in all the ways I have seen it fail?

So far I can see these rules:

- Do not lock the database file (Brave and FF)
- Enable WAL, journal is not enough (Brave, though there seems to be a `History-wal` file)
- Do not truncate the WAL on shutdown or restart (or at all?) (FF)

With Brave:

```
litestream v0.3.2
initialized db: /Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History
replicating to: name="s3" type="s3" bucket="mybucket" path="Brave-History.sqlite" region=""
/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History: sync error: enable wal: database is locked
...
/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History: sync error: ensure wal exists: no such table: _litestream_seq
...
/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History: sync: new generation "d051be38c06dbfe0", no generation exists
/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History(s3): snapshot: creating d051be38c06dbfe0/00000000 t=190.91946ms
/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History: sync error: cannot verify wal state: stat /Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/History-wal: no such file or directory
...
```

With Firefox

```
$ litestream replicate places.sqlite s3://mybucket/Firefox-History.sqlite
litestream v0.3.2
initialized db: /Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite
replicating to: name="s3" type="s3" bucket="mybucket" path="Firefox-History.sqlite" region=""
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite: sync error: enable wal: database is locked
...
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite: sync error: _litestream_lock: no such table: _litestream_lock
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite: sync error: ensure wal exists: no such table: _litestream_seq
...
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite: sync error: cannot verify wal state: stat /Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite-wal: no such file or directory
...
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite: sync: new generation "bdf080e3a79aab8f", wal truncated by another process
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite(s3): snapshot: creating bdf080e3a79aab8f/00000000 t=15.509471996s
/Users/me/Library/Application Support/Firefox/Profiles/myprofile.dev-edition-default/places.sqlite: sync error: checkpoint: mode=PASSIVE err=disk I/O error: errno 260
...
```

**Comment by berezovskyi** [comment]
Also, despite all the errors, I seem to have a reasonable stream of WAL (pages?). Did I mistaken some of the warnings for errors? Or are there some errors that are not considered critical?

![image](https://user-images.githubusercontent.com/64734/107859217-3ae14d80-6e38-11eb-9d5c-daafd4e77934.png)

**Comment by berezovskyi** [comment]
Update: I managed to get it to work (without warnings or errors so far). Changes:

- Use Box Sync as the app
- Start litestream before Box

Every time I add a file to Box, I see a new compressed WAL page appear on S3. Still, the original question remains: what do I have to (not) do for the litestream replication to go smoothly?

Again, thank you for your hard work and kindly open-sourcing it!

**Comment by benbjohnson** [comment]
@berezovskyi Thanks for reporting the bug. Looks like there's an issue with initialization if the database is locked when you start up Litestream. I added an issue for it: https://github.com/benbjohnson/litestream/issues/59

There are some `"database locked"` errors that can be reported during the S3 snapshot but I'm fixing those as well. Litestream will automatically move the database to WAL mode so you shouldn't have to do anything to an existing SQLite database to make it work. If you're seeing errors then those are likely bugs. Litestream keeps a read-only lock on the database too which prevents other applications from checkpointing or truncating the WAL.

The one exception would be if your application is running in [`EXCLUSIVE` locking mode](https://www.sqlite.org/pragma.html#pragma_locking_mode) and only one process can use the database. That's not very typical though.

**Comment by benbjohnson** [comment]
The initialization issue should be fixed now: https://github.com/benbjohnson/litestream/pull/82

**Comment by azappella** [comment]
@berezovskyi @benbjohnson Just thought I'd add something here, Firefox is actually running in Exclusive locking mode. You can toggle that mode off by going into firefox config (-> typing about:config in the search bar) and toggling `storage.sqlite.exclusiveLock.enabled` to false.
