### ISSUE TITLE
Update or remove the "blog" at https://litestream.io/blog/

### ISSUE THREAD

**Issue by Gaibhne** [benbjohnson/litestream#581]
I almost skipped this project, thinking it was completely abandoned, because the blog showed the last release being from 2021. If the blog at https://litestream.io/blog/ is no longer updated, it should be removed from the page; if it receives updates but no release updates anymore, then there should be a new update with that info, otherwise, other people like me who investigate the project and click on the blog might pass on the project purely due to thinking it has been abandoned, which would be a shame.

**Comment by benbjohnson** [comment]
That seems like a good idea. I removed all the blog posts except [this one](https://litestream.io/blog/why-i-built-litestream/) which gives some historical context. I also removed the "Blog" link in the nav. 👍
