### ISSUE TITLE
no .db file found in the replication server

### ISSUE THREAD

**Issue by Nemos** [benbjohnson/litestream#606]
Hello,
I am using litestream sftp replication with ssh keys and the yml configuration file as 
dbs:
  - path: /DATA/IEM/iem.db
    replicas:
      - url: sftp://info@<serverip>/home/info/backup/DATA
        key-path: /home/<username>/.ssh/id_rsa
at the server side I can see the folder generations folder inside DATA folder but there isn't the expected iem.db file inside.
What I am missing or doing wrong ?

**Comment by mohammed90** [comment]
You will not see a single `.db` file at the server. You'll see a tree containing `.lz4` files like this
```
$ tree test/
test/
└── generations
    └── f249fbbdece8354d
        ├── snapshots
        │   └── 00000000.snapshot.lz4
        └── wal
            ├── 00000000_00000000.wal.lz4
            ├── 00000000_00004080.wal.lz4
            ├── 00000000_00005098.wal.lz4
            ├── 00000000_000060b0.wal.lz4
            ├── 00000000_000070c8.wal.lz4
            ├── 00000001_00000000.wal.lz4
            ├── 00000001_00001038.wal.lz4
            ├── 00000001_00002050.wal.lz4
            ├── 00000001_00003068.wal.lz4
            ├── 00000001_00004080.wal.lz4
            ├── 00000001_00005098.wal.lz4
            └── 00000001_000060b0.wal.lz4
```

They can be used to assemble the `.db` file again when restored.

**Comment by Nemos** [comment]
Thank you mohammed, can I restore it to the same space as those files located ?

**Comment by mohammed90** [comment]
> Thank you mohammed, can I restore it to the same space as those files located ?

Kinda defeats the point of Litestream, but you'll have to run Litestream on the remote server with the `restore` command.

That said, you might be more interested in [LiteFS](https://fly.io/docs/litefs/).

**Comment by Nemos** [comment]
Are you sure that will not create a db file ? as at this example for restoring
 litestream restore -o /tmp/my.db s3://mybkt.litestream.io/my.db
specify my.db file in my case doesn't exists

**Comment by Nemos** [comment]
no db file is generated , although this will help a lot, you can always use restore command to "generate" the database where you like.

**Comment by Nemos** [comment]
no db file is generated , although this will help a lot, you can always use restore command to "generate" the database where you like.
