### ISSUE TITLE
Memory utilization seems to scale with DB size

### ISSUE THREAD

**Issue by rishi-kulkarni** [benbjohnson/litestream#613]
First of all, thanks for this great piece of software. I've been running it in production for nearly two years now. Specifically, we run it in an AWS ECS cluster, with the Litestream task running in a separate service than our application. This gives us both the ability to redeploy the app without interrupting Litestream, as well as giving us some insight into the CPU/memory usage of Litestream itself. 

I've noticed some troubling behavior regarding resource utilization usage:

![image](https://github.com/user-attachments/assets/594f4f43-aeae-49f5-933f-211480ffe092)

![image](https://github.com/user-attachments/assets/441da343-48ba-4f8e-a40a-b6b377c9caa8)

The DB is about 1.2 GB right now and has been growing at a steady pace, and the memory utilization percentage seems to imply that the Litestream container is sitting on an average of 1.2 GB of memory right now. This isn't a huge deal (at this pace of DB growth, we have a very long time until this causes issues), but I'd like to resolve any issues before the task OOMs. As far as I can tell, the specific operation that eats up a ton of memory is making a snapshot. 

I tried stopping the task and restarting it (the big drop a few days ago), but memory usage shot right back up after the first snapshot. 

As another piece of evidence, we recently started backing up an existing DB (roughly 1.5 GB in size), and memory utilization shot up after the first snapshot. Note that the Litestream container ballooned to using roughly 1.5 GB of memory at that time. 

![image](https://github.com/user-attachments/assets/ce6b5883-d897-4f08-a786-63613b2d6cd0)

![image](https://github.com/user-attachments/assets/9c06e630-329e-4e35-b48e-421f69a70529)

Additionally, I don't see any errors in the logs, so this is probably unrelated to #562

**Comment by rishi-kulkarni** [comment]
Additional notes - each CPU usage spike is about 2 hours long, but the Litestream logs indicate that snapshotting occurs somewhere in the middle of that spike and only takes about 9 seconds. Is there something else that occurs pre-snapshot that could use a bunch of memory?

**Comment by rishi-kulkarni** [comment]
After further experimentation, this issue is resolved by setting GOMEMLIMIT in the Docker container. Probably yet another instance of Go interacting weirdly with Docker.

**Comment by pbedat** [comment]
> After further experimentation, this issue is resolved by setting GOMEMLIMIT in the Docker container. Probably yet another instance of Go interacting weirdly with Docker.

can you expand a little on this one?
I'm currently noticing litestream to consume more and more cpu every day, even when idling. I think it's connected to memory consumption + GC, but I did not yet find the time for further analysis.

![Image](https://github.com/user-attachments/assets/321b240b-e0f5-4364-a9a7-7e5cad4f9d57)
![Image](https://github.com/user-attachments/assets/e5bfb699-c01b-45e5-93ed-c77f5298572b)

**Comment by rishi-kulkarni** [comment]
@pbedat Interestingly, I haven't observed that CPU problem. I've actually revised my opinion about memory usage - I think part of the issue is that ECS is incorrectly reporting (because Docker also incorrectly reports this) the memory used by inode and dentry slabs (see [here](https://github.com/docker/cli/issues/3171)), which are probably allocated as a part of managing the shadow WAL. 

However, setting GOMEMLIMIT helped... ish. You can see a big drop in memory usage in November when I decided to set GOMEMLIMIT, but usage still creeps up over time. Forcing a redeployment sort of "resets" it, though, hence my current kernel slab hypothesis. I haven't actually seen any containers getting OOM killed, so I decided maybe I was worried about nothing. 

![Image](https://github.com/user-attachments/assets/c71efc15-2ae7-4a39-9557-6b043d59cf3c)
