### ISSUE TITLE
Files replication

### ISSUE THREAD

**Issue by gedw99** [benbjohnson/litestream#63]
The design of lite stream is pretty nice 

I am planning to kick the tires to use is in a master slave setup with minio 

one thing that I am curious about is files being replicated as I have to also be able to store files and replicate changes and minio is excellent at that but I was more curious about if SQLite can store files ?

mit could be an anti pattern too so tell if you think it’s a bad idea

**Comment by benbjohnson** [comment]
> I am planning to kick the tires to use is in a master slave setup with minio

Litestream doesn't currently support a primary/replica set up although that should be coming in the v0.4.0 release. Right now it's meant to give durability to a single instance.

> one thing that I am curious about is files being replicated as I have to also be able to store files and replicate changes and minio is excellent at that but I was more curious about if SQLite can store files ?

You can store blobs in SQLite but it's going to be less efficient than storing in minio directly. Unless you need your files to be transactional, I would avoid it personally.
