### ISSUE TITLE
Windows support, testing & builds

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#7]
Litestream has not been tested against Windows. It probably doesn't work but it also probably wouldn't take much to make it work. This requires testing and release builds added.

Related information for Windows packaging: https://github.com/goreleaser/goreleaser/issues/1295

**Comment by orware** [comment]
We currently use a product from a company called Evisions in the higher education space for reporting needs. Their software runs on Windows, but uses a SQLite database underneath the hood to hold its configuration data and I'd be curious if Litestream could be used to easily replicate that database on a regular basis to another server for example (their software also logs some audit/usage info back to the SQLite database so being able to copy the file over to a different server we use for Dashboarding needs would be helpful since that server can't easily access the SQLite file otherwise, so that's one potential use case I'm thinking we might find Litestream usable in our environment).

If a Windows build is added I'd be happy to try and run some tests with it in our environment :-).

**Comment by benbjohnson** [comment]
Thanks for reaching out, Omar. I'll get a Windows build together soon—hopefully next week.

A few questions: Are your two computers connected on a network? Or do you need to stream the database changes to something like S3 and then the dashboard server pulls it down? How large is the database? And how frequently do you need the dashboard server updated? e.g. is it continuously updated or once a day?

**Comment by orware** [comment]
Thanks Ben for the reply!

The two computers can communicate with each other currently over our internal campus network and I can likely create a Windows fileshare on the Metabase (dashboarding server) VM to make it easier for the Evisions/Argos VM to regularly stream/copy the SQLite database changes to (we're not that sophisticated to be using S3 for any data needs currently, although we do have access to Azure Blob File storage).

I don't know the exact size of the SQLite database but I'm confident it's relatively small (probably a few hundred MBs tops if that, but I can check directly if you need me to). Having the dashboard able to be kept relatively current for that particular information would be nice but if it did need to be delayed that's probably fine too for our needs.

**Comment by edwinyzh** [comment]
Can't wait for the availability of Windows support and test!

**Comment by benbjohnson** [comment]
I was able to get Litestream building and successfully running on Windows with https://github.com/benbjohnson/litestream/pull/34. I need to set up a VPS to continuous test it though and I need to set up CI to create release builds.

If you have Go installed, you can also install [TDM-GCC](https://jmeubank.github.io/tdm-gcc/download/) and run this to install:

```sh
C:\Users\benbjohnson\src\litestream> go install .\cmd\litestream
```

**Comment by benbjohnson** [comment]
I'm not a Windows developer so this took _waaay_ longer than I expected. I was able to get Litestream packaged up and running as a Windows Service so it will run in the background. I also obtained a code signing certificate so hopefully you don't get too many scary warning messages when trying to run the code.

You can find the `.msi` file on: https://github.com/benbjohnson/litestream/releases/tag/v0.3.3-beta1

I'd love to hear feedback from folks if they get a chance to test it. If you have problems, please post a new issue.


### Setup & Install

I'll add a guide on the documentation site but the setup should be:

1. Download the MSI and double click to install.
2. In the `Services` application, you should see _Litestream_ running.
3. You'll need to add a config file to: `C:\Litestream\litestream.yml`
4. Go back to the `Services` application and restart the service after changing the config.

You can find logs in the Windows Event Viewer application. You can also list Litestream events in PowerShell using:

```sh
Get-EventLog -LogName Application -Source Litestream
```
