### ISSUE TITLE
Incorrect key in example litestream.yml

### ISSUE THREAD

**Issue by mtlynch** [benbjohnson/litestream#72]
In the default litestream.yml file, it shows an S3 URL keyed by `path`:

https://github.com/benbjohnson/litestream/blob/6a90714bbe15b3fb272cae19ebe81e7835fe12ca/etc/litestream.yml#L9

The documentation seems to say that this key should be `url` instead:

https://litestream.io/reference/config/#replica-settings

**Comment by benbjohnson** [comment]
Good catch! Thanks for reporting the issue. It's fixed in https://github.com/benbjohnson/litestream/pull/73
