### ISSUE TITLE
npm support for litestream

### ISSUE THREAD

**Issue by o1lab** [benbjohnson/litestream#77]
@benbjohnson : First up, want to say that litestream is amazing piece of work 👍 

Can litestream be published as an npm package ? [go-npm](https://www.npmjs.com/package/go-npm) can help.

**Comment by benbjohnson** [comment]
Thanks! I'm not opposed to doing an npm package but can you give me some details about the workflow and how you use it? Is it just so you can run `npm install` and you have the binary available locally? What's the benefit to that over using Homebrew or other installation techniques?

**Comment by o1lab** [comment]
The idea behind is to use litestream commands programmatically as APIs.

Eg: We want to backup sqlite file whose path is know at run time. So want to prepare the litestream yml and (re)start litestream within our code. As a workaround, this can be done by running shell scripts within nodejs. But having an API would make it better.

**Comment by benbjohnson** [comment]
@o1lab That makes sense. I'm a little hesitant to bundle it with the expectation of using it as an API. I don't feel like I can commit to a consistent API right now as it's still a bit in flux.

**Comment by o1lab** [comment]
@benbjohnson : sure, no worries. I understand its early days now.

Would it be possible to watch sqlite files within a folder ? Currently I understand each file needs a yml entry.

**Comment by benbjohnson** [comment]
Yes, it's something I'm planning to add. I don't think it'll be too difficult but I want to make sure the simple case works well first before adding wildcards. There's a ticket for it here: https://github.com/benbjohnson/litestream/issues/42

**Comment by o1lab** [comment]
Thank you!

**Comment by benbjohnson** [comment]
I'm going to close this issue for now and it can be re-evaluated after a 1.0 release and the API is stable.
