### ISSUE TITLE
Errors in replication?

### ISSUE THREAD

**Issue by johnsonjsyuen** [benbjohnson/litestream#78]
Hi, getting this when running replicate 
```
/home/xxx/datadrive/code/nzquarantine/storage.db: sync error: create generation: initialize shadow wal: read header: EOF

/home/xxx/datadrive/code/nzquarantine/storage.db: sync: new generation "21b638752c28dcb5", wal overwritten by another process

/home/xxx/datadrive/code/nzquarantine/storage.db(s3): snapshot: creating 21b638752c28dcb5/00000000 t=56.330497ms
```

Command run: ```litestream replicate storage.db s3://xxx```

I am able to restore but it is missing latest data.

Tested with AWS S3 on Linux 64bit. Sqlite being used by Python standard library, no Sqlachemy or anything

Only using a single python process that is singlethreaded.

**Comment by johnsonjsyuen** [comment]
On restart its working normally with no changes to environment

**Comment by benbjohnson** [comment]
@johnsonjsyuen Thanks for reporting this. I believe this is related to https://github.com/benbjohnson/litestream/issues/59 which should be fixed later today. I'm going to close this in favor of that ticket.

**Comment by benbjohnson** [comment]
This should be fixed now with https://github.com/benbjohnson/litestream/pull/82
