### ISSUE TITLE
Bucket Autocreation

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#83]
Currently, you must create a bucket on an S3-compatible store before replicating. This adds an extra step that could be handled by `litestream` if it finds that a bucket doesn't exist. This would simplify the _Getting Started_ page as well.

**Comment by yanc0** [comment]
Hi, 

Just thinking that this feature will require wide permissions to do that (storage admin). I'd rather do the bucket myself or via automation tools I think. Moreover, you will have to deal with some provider implementations as sometimes, S3 is more of a compatibility mode than a real standard (GCS for example).

To me, I'd prefer a good old explicit fatal error than a magically created bucket but it's just my opinion :)

Have a good day !

**Comment by benbjohnson** [comment]
Thanks for the feedback. I'll move this to a "proposal" to get more feedback. Maybe bucket autocreation could happen if someone is using the replica URL on the CLI? I'm not sure. I'll think about it some more.

**Comment by benbjohnson** [comment]
I'm closing this as magic bucket creation probably isn't a great idea. :)
